### ISSUE TITLE
Warning: Unable to clean or reset the repository. The repository will be recreated instead.

### ISSUE THREAD

**Issue by awolad** [Azure/static-web-apps#543] opened 2021-08-10 05:41 UTC
**It's a react app.**

**My workflow yml**

```
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - development
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - development

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_BALL}}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '/' # App source code path
          api_location: 'api' # Api source code path - optional
          app_artifact_location: 'dist' # Built app content directory - optional
          app_build_command: 'npm run build:development'
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - run: yarn install
      # - run: yarn test
      ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_BALL }}
          action: 'close'

```

**Error log:**

```
Run actions/checkout@v2
Syncing repository: testAd/testAd
Getting Git version info
/usr/bin/git config --local --get remote.origin.url
https://github.com/testAd/testAd
Removing previously created refs, to avoid conflicts
Cleaning the repository
  /usr/bin/git clean -ffdx
  warning: failed to remove dist/google-assistant.png: Permission denied
  warning: failed to remove dist/assets/images/profile-default.png: Permission denied
  warning: failed to remove dist/20.bundle.js: Permission denied
  warning: failed to remove dist/alexa.png: Permission denied
  warning: failed to remove dist/firebase-messaging-sw.js: Permission denied
  warning: failed to remove dist/14.bundle.js: Permission denied
  warning: failed to remove dist/23.bundle.js: Permission denied
  warning: failed to remove dist/19.bundle.js: Permission denied
  warning: failed to remove dist/5.bundle.js: Permission denied
  warning: failed to remove dist/favicon-32x32-transparent.png: Permission denied
  warning: failed to remove dist/18.bundle.js: Permission denied
  warning: failed to remove dist/routes.json: Permission denied
  warning: failed to remove dist/2.bundle.js: Permission denied
  warning: failed to remove dist/9.bundle.js: Permission denied
  warning: failed to remove dist/21.bundle.js: Permission denied
  warning: failed to remove dist/static-data/tts.json: Permission denied
  warning: failed to remove dist/bundle.js: Permission denied
  warning: failed to remove dist/android-chrome-512x512.png: Permission denied
  warning: failed to remove dist/15.bundle.js: Permission denied
  warning: failed to remove dist/apple-touch-icon.png: Permission denied
  warning: failed to remove dist/android-chrome-192x192.png: Permission denied
  warning: failed to remove dist/4.bundle.js: Permission denied
  warning: failed to remove dist/favicon.ico: Permission denied
  warning: failed to remove dist/0.bundle.js: Permission denied
  warning: failed to remove dist/3.bundle.js: Permission denied
  warning: failed to remove dist/22.bundle.js: Permission denied
  warning: failed to remove dist/8.bundle.js: Permission denied
  warning: failed to remove dist/logo.png: Permission denied
  warning: failed to remove dist/13.bundle.js: Permission denied
  warning: failed to remove dist/17.bundle.js: Permission denied
  warning: failed to remove dist/favicon-32x32.png: Permission denied
  warning: failed to remove dist/11.bundle.js: Permission denied
  warning: failed to remove dist/favicon-16x16.png: Permission denied
  warning: failed to remove dist/1.bundle.js: Permission denied
  warning: failed to remove dist/16.bundle.js: Permission denied
  warning: failed to remove dist/10.bundle.js: Permission denied
  warning: failed to remove dist/12.bundle.js: Permission denied
  warning: failed to remove dist/7.bundle.js: Permission denied
  warning: failed to remove dist/index.html: Permission denied
  warning: failed to remove dist/site.webmanifest: Permission denied
  warning: failed to remove dist/6.bundle.js: Permission denied
  Removing node_modules/
  Removing package-lock.json
Warning: Unable to clean or reset the repository. The repository will be recreated instead.
Deleting the contents of '/home/runner/work/testAd/testAd'
Error: Command failed: rm -rf "/home/runner/work/testAd/testAd/dist"
rm: cannot remove '/home/runner/work/testAd/testAd/dist/google-assistant.png': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/assets/images/profile-default.png': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/20.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/alexa.png': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/firebase-messaging-sw.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/14.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/23.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/19.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/5.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/favicon-32x32-transparent.png': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/18.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/routes.json': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/2.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/9.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/21.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/static-data/tts.json': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/android-chrome-512x512.png': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/15.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/apple-touch-icon.png': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/android-chrome-192x192.png': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/4.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/favicon.ico': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/0.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/3.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/22.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/8.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/logo.png': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/13.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/17.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/favicon-32x32.png': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/11.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/favicon-16x16.png': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/1.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/16.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/10.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/12.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/7.bundle.js': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/index.html': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/site.webmanifest': Permission denied
rm: cannot remove '/home/runner/work/testAd/testAd/dist/6.bundle.js': Permission denied
```

**Comment by anthonychu** [comment] 2021-08-15 05:59
Looks like this may be caused by the second `actions/checkout@v2` action in your workflow. It's trying to checkout your repo again, and ran into issues deleting files generated by when the app was built in the previous step.

```yml
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
```

Try removing the ` - uses: actions/checkout@v2` line and try again.

**Comment by awolad** [comment] 2021-08-16 05:01
@anthonychu Ok, I'll try by removing the line. Thanks!

**Comment by awolad** [comment] 2021-08-19 09:07
It worked. Thanks @anthonychu

**Comment by Reshmi-Sriram** [comment] 2023-04-10 10:56
Marking as resolved

**Closed by Reshmi-Sriram** 2023-04-10 10:56 UTC
