### ISSUE TITLE
Deployments are failing due to 'An error occurred during deployment'

### ISSUE THREAD

**Issue by jasoncabot-ms** [Azure/static-web-apps#71] opened 2020-06-18 15:33 UTC
I have two seperate repositories, two seperate static web app resources. The code is identical in the two repositories (the second is a clone of the first).

For both of these repositories I am able to build but not deploy the code, here are the build/deploy logs with the failure:

one: https://github.com/jasoncabot-ms/divineflavours-webapp/runs/784852058?check_suite_focus=true#step:4:222
two: https://github.com/jasoncabot-ms/divine-flavours/runs/784913503#step:4:223

The strange thing is I had this code deploying fine before in a different repository but then it started failing and now it fails 100% of the time.

Is there any more information that can be written to the logs to help diagnose what the underlying error is?

**Comment by aelgasser** [comment] 2020-06-18 16:26
So I'm not the only one experiencing this. 

My function doesn't show up anymore in the portal and when I try to invoke it with Postman I'm receiving '503 Service Unavailable" as a response.

**Comment by jmcaree** [comment] 2020-06-18 22:35
I'm having the same issue, I've been just trying to get my first static web app with a function deployed to Azure today, following with a few of the walkthroughs. A React app cloned from the [template repo](https://github.com/staticwebdev/react-basic) deploys to Azure fine:
https://github.com/jmcaree/afreact/actions/runs/140175487

But a basic app with an Azure Function cloned from the [Vanilla App repo](https://github.com/staticwebdev/vanilla-basic) (Function app added following How-to [here](https://docs.microsoft.com/en-us/azure/static-web-apps/add-api)) is failing to deploy:
https://github.com/jmcaree/afreactapi/runs/786166141?check_suite_focus=true#step:4:111

Same error as @jasoncabot-ms. It looks like something is timing out, and the deploy simply fails.

**Comment by jasoncabot-ms** [comment] 2020-06-19 08:18
I'm not sure if it's just a coincidence but I saw an annotation added on the workflow run that `repo_token` was an invalid option to pass to the action.

I commented it out from the action and now the action seems to be building and deploying correctly again.

https://github.com/jasoncabot-ms/divine-flavours/commit/c28044c9f34982769ac84c81d750e50084eb2812#diff-43750e28cedb6a52a257c926b957b9c9

https://github.com/jasoncabot-ms/divine-flavours/runs/787318131

Is this expected?

**Comment by aelgasser** [comment] 2020-06-19 11:10
@jasoncabot-ms, I don't think so (or maybe you were having another issue). 

I tried redeploying my repo earlier (3 hours ago) and it deployed successfully. I did nothing more than re-run the github action which was failing yesterday

**Comment by jmcaree** [comment] 2020-06-19 11:14
> I'm not sure if it's just a coincidence but I saw an annotation added on the workflow run that `repo_token` was an invalid option to pass to the action.
> 
> I commented it out from the action and now the action seems to be building and deploying correctly again.

This has fixed my issue also, commenting out the repo token has allowed my app to deploy through the GitHub action.

**Comment by miwebst** [comment] 2020-06-19 18:34
Sorry for the confusion here, we have created an observability work item to make this issue more apparent. This deployment issue was caused by an issue with Azure Functions in West Europe yesterday. We fixed the issue which may be why commenting out the repo_token looked like the correct mitigation, but it was most likely unrelated.

We apologize for the inconvenience and are figuring out the best ways to share our platform status and how to improve our Github Action logs to clarify when things are having issues. Thank you for your patience and hopefully things have returned to normal now!

**Comment by aelgasser** [comment] 2020-06-19 18:45
@miwebst, So that probably explains my other issue #70 as well, as I saw in the network trace it was failing on a "fetchFunctions" API call. I had no issues today.

**Comment by miwebst** [comment] 2020-06-19 18:48
Yes that would be the cause. This is good to note, we can improve our Azure Portal experience as well to give more information if any outage occurs.

**Comment by aelgasser** [comment] 2020-06-19 19:16
@miwebst look at #69 then as well, re the portal experience :-)

**Comment by miwebst** [comment] 2020-06-22 18:36
Going to close this out as the issue has recovered, we will take a look at #69 though!

**Closed by miwebst** 2020-06-22 18:36 UTC

**Comment by diverdan92** [comment] 2020-06-25 23:33
@miwebst I'm hitting this issue today. I can deploy the application if I remove the api, but trying to deploy a static web app _with_ a function fails. Do you know if there is another service issue occuring? 
![image](https://user-images.githubusercontent.com/6608201/85805597-9de37000-b701-11ea-8f12-4437d67671ef.png)

**Comment by miwebst** [comment] 2020-06-25 23:39
Hi @diverdan92, there is an issue ongoing :( we are working on a fix. Sorry for the inconvenience, @dariagrigoriu we need to work on a status page for people to check with.

**Comment by diverdan92** [comment] 2020-06-25 23:40
Thanks for the quick reply :).

FWIW, my first inclination after realizing it only reproduced for functions deployment was to go to the [Azure Status](https://status.azure.com/en-us/status) page.

**Comment by miwebst** [comment] 2020-06-26 01:20
Thats a great point, we will need to get updates there. We have failed over, this should be fixed now.

**Comment by tburkins** [comment] 2020-06-27 18:27
Hi @miwebst, I've been seeing this issue yesterday and today on my static web app hosted in East US2.  It's the same behavior, where the deployment only succeeds if I remove the API.

![image](https://user-images.githubusercontent.com/26844554/85929258-f721df80-b878-11ea-8c42-aff77978f9e1.png)

**Comment by miwebst** [comment] 2020-06-29 20:48
Hi @tburkins , yes this was caused by an underlying dependency going down. We failed over to a different region but later on the dependency went down in our failover region. We are working to improve our recovery in these scenarios and I apologize for the issue! It should be fixed now, please let us know if you continue to see issues.

**Comment by tburkins** [comment] 2020-06-29 21:09
Thanks for replying @miwebst, it started working yesterday and I haven't had any more issues with it.
