### ISSUE TITLE
Oryx has timed out while building app

### ISSUE THREAD

**Issue by Arshad707in** [Azure/static-web-apps#1134] opened 2023-04-11 06:02 UTC
I am building a small size angular application and Build and deploy action is getting timeout after successful compilation.
There are no logs except below :

---End of Oryx build logs---
Oryx has timed out while building app, the current limit is 15 minutes. Failing build.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting

**Comment by jacob-amptech** [comment] 2023-04-12 14:00
Not an Azure guy.

Assuming the logs you posted directly above are the ones you receive when deploying, it looks to me like you're trying to run the Angular Development Server on Azure Static Sites.

This makes sense that it would timeout, as once the development server is running, it will continue to run until shut down or restarted.

The command you might be looking for instead of 'ng serve' is 'ng build --configuration production' to build the application into a static site, upon which you can then deploy said built application to Azure Static Web Apps.

**Comment by thomasgauvin** [comment] 2023-04-20 17:52
@jacob-amptech seems to be looking in the right direction, your build logs @Arshad707in indicate that you are running an Angular Dev Server during your build command. Your build command should instead build your project. Can you share your repo, so we can see your package.json configuration? It seems possible that the 'build' command is ng serve instead of ng build

**Comment by thomasgauvin** [comment] 2023-05-18 18:45
@brentarias, I see that you've opened a separate issue, and I've replied in there with details about how to increase the build timeout https://github.com/Azure/static-web-apps/issues/1161 Let me know if this solves your issue in that thread.

Regarding this thread, I propose closing as this seems caused by the build command being misconfigured as pointed out by @jacob-amptech. If this did not resolve your issue @Arshad707in, we can reopen this thread

**Closed by thomasgauvin** 2023-05-18 18:45 UTC
