### ISSUE TITLE
Bicep/ARM deploy with provider "Devops" and Azure Repos as the url. Fails with invalid repository token.

### ISSUE THREAD

**Issue by MichielCornilleKenze** [Azure/static-web-apps#771] opened 2022-03-29 07:47 UTC
This pipeline ran perfectly for a while but some recent changes must have broken something, because now the repository token needs to be provided even when specifying provider:'DevOps" which in the past wasn't  necessary for Bicep/ARM deploys.

`resource webApp 'Microsoft.Web/staticSites@2021-03-01' = {
  location: location
  name: 'stapp-${resourceName}-${environment}'
  properties: {
    provider: 'DevOps'
    repositoryUrl: repositoryUrl
    **// repositoryToken:  repositoryToken** => did not specify this in the past.
    branch: repositoryBranch
    buildProperties: {
      skipGithubActionWorkflowGeneration: true
    }
  }
  sku: {
    name: sku
    tier: skuTier
  }
}`

I tried to work around this by creating an Azure DevOps PAT with repository read access but and setting that as the token, but this throws a different error:

'There was an unexpected InternalServerError.  Please try again later.  x-ms-correlation-request-id: 0d048cb0-2305-4a63-bb35-ab0b794efee5'

I tried a differentn workaround leaving the repository url empty as we don't really need that (we want to deploy into staticapps) but that throws a validation error as the repository url seems to be required.

I tried with different versions of the API (2021-03-01 and the 2021-02-01 version and both seem to have the same behavior.
Setting a completely bogus repository token causes a 500 error.

What's the story here? Did anything change on Microsoft's end? Is Azure Repos still supported?

We are not using Oryx (disabled app build and disabled github workflow generation) as we do not use Github.

**Comment by jslowack** [comment] 2022-03-29 08:02
We have the same issue, I think it is related to https://github.com/Azure/static-web-apps/issues/767

**Comment by miwebst** [comment] 2022-03-29 22:41
We are working on a fix for this! Apologize for the inconvenience.

**Comment by chrisjensenuk** [comment] 2022-03-30 08:17
Thanks for the update @miwebst

I have the same problem - using Bicep to deploy a SWA from DevOps which used to work until yesterday. This is currently blocking us. Is there an ETA for this fix? Is there a known work around we can use in the meantime? Thanks

**Comment by william-liebenberg** [comment] 2022-03-30 22:19
Same issue here :( any temp workarounds available?

**Comment by chrisjensenuk** [comment] 2022-04-01 14:16
We've implemented a workaround for this issue. Just thought I'd share.
```
resource staticWebApp 'Microsoft.Web/staticSites@2021-03-01' = {
  name: pStaticWebAppsName
  location: pLocation
  tags: pTags
  sku: {
    name: pStaticWebAppsSkuName
    tier: pStaticWebAppsSkuTier
  }
  properties:{
    provider : (empty(pStaticWebAppsRepositoryUrl)) ? null : 'DevOps'
    repositoryUrl : (empty(pStaticWebAppsRepositoryUrl)) ? null :  pStaticWebAppsRepositoryUrl
    branch : (empty(pStaticWebAppsRepositoryUrl)) ? null :  pStaticWebAppsBranch
  } 
}
```
1. When first initially creating the swa resource ensure `pStaticWebAppsRepositoryUrl` is `""`
2. Deploy the swa front-end application via a DevOps pipeline
3. Update `pStaticWebAppsRepositoryUrl` back to the repo of the DevOps pipeline repository
4. Subsequent infrastructure deployments to the existing swa resource will be OK.

As an aside. It would be great if we didn't have to specify `provider `, `repositoryUrl` or `repositoryUrl ` at all.

**Comment by MichielCornilleKenze** [comment] 2022-04-04 11:29
Great to hear you are working on a solution.

> As an aside. It would be great if we didn't have to specify `provider `, `repositoryUrl` or `repositoryUrl ` at all.

Continuing on that aside: As soon as you have more than one environment(Dev/QA/Prod,..) We want to do a more traditional 12-factor app style BUILD/Release separation. Oryx /static apps wants to do too much at once. It might make sense to run Oryx inside Azure DevOps or Github actions but I don't think static apps should be the initiator...

**Comment by jiaojiaoxia** [comment] 2022-04-07 09:27
Hi All, has the issue been resolved? I am still having it and it blocks our deployment for a week now.

**Comment by mmrepos** [comment] 2022-04-12 06:08
@MichielCornilleKenze @jiaojiaoxia Could you confirm that you are providing repository token with right permisions as we need to have enough permissions to make changes to their repository, which wasn't the case before. The workaround for this is that they'd have to use a PAT token with these minimal permissions - Build(Read & Execute); Code(Read, write, & manage); Variable Groups(Read, create, & manage)

**Comment by jiaojiaoxia** [comment] 2022-04-12 09:27
Hi @mmrepos, yes, found out when I filled in the repository token, then the deployment works again. Thanks.

**Comment by mrdobing** [comment] 2022-04-13 14:54
Hey, @jiaojiaoxia, @mmrepos... can you kindly explain the workaround for this issue please?
I have a vue app that deploys to a static web app via azure pipeline and I'm getting a repository token invalid issue.

Sorry, I'm not an experienced dev so a little walkthrough would be really appreciated to get this up and running again !

**Comment by joedevgee** [comment] 2022-04-14 03:31
> 

exactly, can we make all the repository related parameters optional? bicep/arm should only provision the resource and let CICD handle the static site deployment

**Comment by miwebst** [comment] 2022-04-18 23:44
We've now made this info optional. You should be able to deploy with ARM/BICEP without needing to introduce CI/CD details.

**Comment by flip-it** [comment] 2022-04-19 07:43
Great! Works good.

**Comment by nicksimmonds-lmk** [comment] 2022-04-19 08:44
This is still not working for me.  I have removed provider, repositoryUrl and branch from our bicep template but when I deploy the template to a static web app that has code deployed to it I still get the error:
RepositoryUrl is invalid.  The repository url does not match the format of a DevOps repository.

**Comment by jiaojiaoxia** [comment] 2022-04-19 09:30
@nicksimmonds-lmk 
The fix I have done is to provide repositoryToken. Here is the arm template I used. The repositoryToken comes from System.AccessToken from agent.
        {
            "type": "Microsoft.Web/staticSites",
            "apiVersion": "2021-02-01",
            "name": "[parameters('staticSiteName')]",
            "location": "West Europe",
            "sku": {
                "name": "[parameters('sku')]",
                "tier": "[parameters('sku')]"
            },
            "identity": {
                "type": "SystemAssigned"
            },                
            "properties": {
                "repositoryUrl": "[parameters('repositoryUrl')]",
                "provider": "DevOps",
                "repositoryToken": "[parameters('repositoryToken')]",
                "branch": "[parameters('branchName')]",
                "stagingEnvironmentPolicy": "Enabled",
                "allowConfigFileUpdates": true
            }
        }

**Comment by nicksimmonds-lmk** [comment] 2022-04-19 09:45
My issue is that I use a bicep template to deploy the Static Web App resource.  I then have a DevOps pipeline that pulls our code from a GitHub repo, builds the code and then deploy the code to the Static Web App.  This then sets the following values on the resource:

branch: main
provider: DevOps
repositoryUrl: https://github.com/xxxxx/xxxxx

The issue is that when I try an deploy the bicep template again I get: RepositoryUrl is invalid. The repository url does not match the format of a DevOps repository.

I get this error if my bicep template provides the branch, provider and repositoryUrl values as above and I get the error if my bicep template does not provide those values.

**Comment by MichielCornilleKenze** [comment] 2022-04-19 14:13
> Hi @mmrepos, yes, found out when I filled in the repository token, then the deployment works again. Thanks.

Is this resolved for existing static apps or does it only work for new static apps? After removing repositorytoken, repositoryurl and branch the static site deployment tells me that it cannot find a static site or the token is invalid which is most definitely not true (the azure resource exists and the token is fetched using ARM/bicep)

**Comment by mrdobing** [comment] 2022-04-19 14:40
@nicksimmonds-lmk, I have a similar setup in devops however our code is in an Azure git repo and not github.
I just commented out any repo properties in the bicep file and my pipeline just worked. Can you import your repo into your azure devops project and try that?

**Comment by MichielCornilleKenze** [comment] 2022-04-19 14:47
> @miwebst Is this resolved for existing static apps or does it only work for new static apps? After removing repositorytoken, repositoryurl and branch the static site deployment tells me that it cannot find the static site or the token is invalid which is most definitely not true (the azure resource exists and the token is fetched using ARM/bicep)

The issue resolved itself on consecutive tries. Deploying seems to be fixed. You can close this issue.

**Comment by nicksimmonds-lmk** [comment] 2022-04-19 14:58
@mrdobing our policy is to use GitHub only for repos.

**Closed** 2022-05-10 11:30 UTC
