### ISSUE TITLE
app_artifact_location is not optional

### ISSUE THREAD

**Issue by lovettchris** [Azure/static-web-apps#4] opened 2020-05-19 22:58 UTC
The static web apps deploy github action template contains:

- "app_artifact_location: '' # Built app content directory - optional"

indicating it is optional, but if I delete it I get a build error, and if I leave it empty I get a build error.  So it appears this is not optional.  

Turns out changing it to this seems to work, perhaps you should fix the template then to do this and remove the word "optional":
- "app_artifact_location: '.' # Built app content directory"

I'm trying to deploy something that is truly a static web app already, no need for build, and no build artifact location: https://github.com/lovettchris/TeleprompterBuild

**Comment by miwebst** [comment] 2020-05-19 23:17
Hi @lovettchris,

Thanks for trying out the product! This is technically optional, but your build may fail if this is not provided. Under the covers, we use Oryx and if Oryx fails to determine the output folder (which is based on some logic that is continually being improved) then we can't upload your assets.

I took a look at your Github Action logs and that is indeed the case. So for your case it is not optional until Oryx improves there detection.

That being said, it is optional in general. If you have a purely static repo (i.e. just your html, css, etc) then you wont need this and it can be removed.

**Comment by miwebst** [comment] 2020-07-24 03:50
Closing this; also confirmed that removing both api_location and app_artifact_location do not lead to a failed build. 

cc @kichalla, in this case Oryx tried to build the application because of the package.json but my guess is failed to find the 'build' command and the end experience was confusing. Since we now require build the error would have been clearer, but this is still a scenario we should take note of: a package.json file but no application build steps.

**Closed by miwebst** 2020-07-24 03:50 UTC
