### ISSUE TITLE
Fatal error in IL Linker 6.0.100-rc.1.21458.32

### ISSUE THREAD

**Issue by Continuitis** [Azure/static-web-apps#590] opened 2021-09-23 15:05 UTC
Hello,

I did update my packages to the latest version of .NET 6 6.0.0-rc.1.21452.15 for my blazor App.
When I try to deploy via Github action I get:

> `ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [/github/workspace/Ui/Ui.csproj]
  Fatal error in IL Linker
  Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
     at Mono.Linker.CustomAttributeSource.HasAny(ICustomAttributeProvider provider)
     at Mono.Linker.AnnotationStore.GetLinkerAttributes[T](IMemberDefinition member)
     at Mono.Linker.AnnotationStore.TryGetLinkerAttribute[T](IMemberDefinition member, T& attribute)
     at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, Nullable`1 origin)
     at Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.MarkAssembly(AssemblyDefinition assembly, DependencyInfo reason)
     at Mono.Linker.Steps.MarkStep.ProcessMarkedPending()
     at Mono.Linker.Steps.MarkStep.Initialize()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink`

![image](https://user-images.githubusercontent.com/83697823/134532876-c42b63f3-f1d2-44b3-88e1-2c9e905b11b5.png)

Any Idea?

Thanks in advance!

**Comment by Continuitis** [comment] 2021-09-24 21:01
Hi,
The repo is private. But I could try to reproduce it if you want. The default Blazor Wasm project should do it I think.

**Comment by anthonychu** [comment] 2021-09-25 20:09
Yes a repro would be great. Thanks.

**Comment by vitek-karas** [comment] 2021-09-27 18:11
This is a duplicate of https://github.com/dotnet/linker/issues/2274.
It should be fixed in RC2.

**Comment by simonaco** [comment] 2021-11-16 11:15
Closing as this should be fixed in GA, @Continuitis let us know if you're still running into issues

**Closed by simonaco** 2021-11-16 11:15 UTC
