### ISSUE TITLE
Static WebApp deployment Action gets stuck Polling Deployment but works fine locally on swa CLI

### ISSUE THREAD

**Issue by osobeso** [Azure/static-web-apps#951] opened 2022-10-14 03:06 UTC
**Describe the bug**
I have a repository (https://github.com/osobeso/TaskifySWA) that I'm trying to deploy to an Azure Static Webapp.
It works fine locally, but when I try to deploy it the Github Action gets stuck on 'Polling Deployment'

```
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.1350726(s)
Status: InProgress. Time: 15.2716099(s)
Status: InProgress. Time: 30.40201(s)
Status: InProgress. Time: 45.5830464(s)
Status: InProgress. Time: 60.7690477(s)
Status: InProgress. Time: 76.1861414(s)
Status: InProgress. Time: 91.287543(s)
Status: InProgress. Time: 106.414874(s)
Status: InProgress. Time: 121.6030543(s)
Status: InProgress. Time: 136.7474857(s)
Status: InProgress. Time: 151.8[257](https://github.com/osobeso/TaskifySWA/actions/runs/3230664788/jobs/5289372895#step:6:258)152(s)
Status: InProgress. Time: 167.0245625(s)
Status: InProgress. Time: 182.2402091(s)
Status: InProgress. Time: 197.4017246(s)
Status: InProgress. Time: 212.5317552(s)
Status: InProgress. Time: 227.7063112(s)
Upload Timed Out. Unsure if deployment was successful or not.
```

**To Reproduce**
1. Go to https://github.com/osobeso/TaskifySWA and fork the repository.
2. Add a deployment token secret from your own Azure static web app into your github action secrets.
3. Run the workflow

**Comment by boy-incerta** [comment] 2022-10-14 06:35
Looks like duplicate of #949

**Comment by vivekjilla** [comment] 2022-10-14 07:33
Related to #949

**Comment by MaxWilson** [comment] 2022-10-14 21:07
Related to #942

**Comment by vivekjilla** [comment] 2022-10-17 04:28
Hi @osobeso this should be resolved now. Please try again and reopen the issue if not resolved. Sorry for the inconvenience.

**Closed by vivekjilla** 2022-10-17 04:28 UTC
