### ISSUE TITLE
`X-Forwarded-Host` header does not work at logout using custom authentication

### ISSUE THREAD

**Issue by beachside-project** [Azure/static-web-apps#712] opened 2022-02-03 06:47 UTC
**Describe the bug**

I setup the  Static Web App custom authentication using Azure AD B2C and login/logout worked fine.
Then I configured Front Door for Static Web Apps by referring to [here](https://docs.microsoft.com/en-us/azure/static-web-apps/front-door-manual).

The login behavior via Front Door URL was working fine. but when logout, the request was redirected to the Static Web App domain as below, so did not work.

It looks to me like a problem of not handling `X-Forwarded-Host` correctly.

![image](https://user-images.githubusercontent.com/11142786/152272364-c8c14710-640e-417f-8c59-6b8608c45885.png)

![image](https://user-images.githubusercontent.com/11142786/152272290-e7115a48-b7c4-49a6-b4e8-ccee97c20796.png)

**To Reproduce**

1. Create Static Web App
2. Setup SWA custom authentication ( in my case, using Azure AD B2C)
3. Create a Front Door and configure Static Web App as a backend
4. Access to `https://{front door domain}/.auth/login/***`
5. Access to  `https://{front door domain}/.auth/logout`

**Device info (if applicable):**
 - OS: Windows 10 (21H1)
 - Browser: Chrome (v97.0.4692.99), Edge (v97.0.1072.76)

**Comment by mkarmark** [comment] 2022-02-04 23:04
Hi @beachside-project, have you configured the networking and forwardingGateway section in your config file? 

Here is the tutorial: https://docs.microsoft.com/en-us/azure/static-web-apps/front-door-manual#update-static-web-app-configuration

Configuring these sections should result in you experiencing the desired flow as well as improve the security of your setup!

**Comment by beachside-project** [comment] 2022-02-07 04:46
Hi, @mkarmark, Thanks for your reply. 
I had already configured the `networking` and `forwardingGateway`, like below link.

https://github.com/beachside-project/swa-api-inv/blob/main/staticwebapp.config.json

This problem is happening in that configuration.

While logout redirect, The location changes from Front Door domain to Static Web App domain. It looks like the relative path of `post_logout_redirect_uri` is not working.

![image](https://user-images.githubusercontent.com/11142786/152725273-f99cfce6-6dc8-4e2e-9790-3155004bcf0c.png)

![image](https://user-images.githubusercontent.com/11142786/152725813-352150ca-5d6c-4ad0-8423-b7ec9e6b1f3c.png)

**Comment by shibayan** [comment] 2022-02-08 09:37
I am also seeing the same problem.

#558 resolved the hostname problem when logging in, but there still seems to be a hostname problem when logging out. As you can see in the current capture, when redirecting to `/.auth/logout/complete`, the hostname changes to the one generated automatically by Static Web App, so the cookie is not deleted correctly and the logout does not take place.

![image](https://user-images.githubusercontent.com/1356444/152956915-ec37434f-853f-4eae-9453-86b96e76b37c.png)

The `staticwebapp.config.json` that we are using will look like the following. The problem occurs even though I have added the `forwardingGateway` setting.

```json
{
  "$schema": "https://json.schemastore.org/staticwebapp.config.json",
  "routes": [
    {
      "route": "/login",
      "rewrite": "/.auth/login/b2c"
    },
    {
      "route": "/logout",
      "rewrite": "/.auth/logout"
    },
    {
      "route": "/*",
      "allowedRoles": [
        "authenticated"
      ]
    }
  ],
  "responseOverrides": {
    "401": {
      "redirect": "/login",
      "statusCode": 302
    }
  },
  "forwardingGateway": {
    "allowedForwardedHosts": [
      "hack-azure.z01.azurefd.net"
    ],
    "requiredHeaders": {
      "X-Azure-FDID": "..."
    }
  },
  "auth": {
    "identityProviders": {
      "customOpenIdConnectProviders": {
        "b2c": {
          "enabled": true,
          ...
        }
      }
    }
  }
}
```

----

Since I was curious, I also checked the behavior of App Service Authentication when logging out, but as in the case of Static Web Apps, the host name changed to the default domain only when logging out, and the logout did not occur correctly.

![image](https://user-images.githubusercontent.com/1356444/152957065-49e99da8-027d-4826-a840-4e3ac0d38fa4.png)

The same problem occurs when `Standard` is set for `forwardProxy`.

**Comment by mkarmark** [comment] 2022-02-09 04:39
We have identified the issue on our end and are working on a fix which we should be able to deploy globally within the next 1-2 weeks. Thanks for your patience!

**Comment by mkarmark** [comment] 2022-02-15 23:36
The fix for this issue has been globally deployed. Can you please retry now and let me know if you are now mitigated?

**Comment by beachside-project** [comment] 2022-02-16 06:10
Thanks a lot ! I checked the logout behavior and work fine !

**Closed** 2022-02-22 13:37 UTC

**Comment by msikka93** [comment] 2023-11-25 10:51
@beachside-project @mkarmark  I am facing similar issue when I try to use azure application gateway in front of Static web app.
Steps to reproduce the behavior:

Create Static Web App
Setup SWA custom authentication ( AAD) in static config json file
Create a Private App Gateway and configure Static Web App as a backend
Set this redirect URL in service principal redirect URLs https://{application gateway custom domain}/.auth/login/aad/callback.

I have the following settings in my config json file
"forwardingGateway": {
    "allowedForwardedHosts": [
      "app gw custom domain",
    ]
  },

Still when I try to access the application it gives me below error:-
The redirect URI 'https://abc-def-xxxxxxxx.x.azurestaticapps.net/.auth/login/aad/callback' specified in the request does not match the redirect URIs configured for the application 'Service Principle Object ID'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

Can you please guide me a little? Where am I going wrong?

Any inputs would be much appreciated
