### ISSUE TITLE
Custom domain or subdomain option for staging

### ISSUE THREAD

**Issue by antonioberetini** [Azure/static-web-apps#37] opened 2020-05-28 13:18 UTC
I just realized that it is not possible to map a subdomain to staging environment. This is very common and useful to help people find staging easily.

**Comment by miwebst** [comment] 2020-05-28 15:22
Hey @antonioberetini I think this may be a duplicate of this issue: https://github.com/Azure/static-web-apps/issues/22

**Comment by antonioberetini** [comment] 2020-05-28 15:25
You are right

**Comment by antonioberetini** [comment] 2020-05-28 15:28
> Hey @antonioberetini I think this may be a duplicate of this issue: https://github.com/Azure/static-web-apps/issues/22 

You are right

**Closed** 2020-05-28 18:47 UTC
Labels: duplicate
