### ISSUE TITLE
GitHub scheduled workflows failing with "Could not parse repository information from event json"

### ISSUE THREAD

**Issue by annaji-msft** [Azure/static-web-apps#82] opened 2020-07-01 16:31 UTC
GitHub scheduled workflows failing with "Could not parse repository information from event json"

Repo workflow with 30m schedule:
https://github.com/anganti/vanilla-api/blob/master/.github/workflows/azure-static-web-apps-proud-ground-0e0cd621e.yml#L12

Sample Run
https://github.com/anganti/vanilla-api/runs/827340906?check_suite_focus=true

![image](https://user-images.githubusercontent.com/42851022/86268788-8ed74480-bb7d-11ea-8c5d-61d056549490.png)

**Comment by BernhardRode** [comment] 2020-07-06 10:57
Same issue here.

**Comment by ssmith04** [comment] 2020-07-06 22:48
Also experiencing this issue; my GitHub action workflow was also modified to run on a cron schedule rather than on push. The rest of the action sets up Ruby to build a Jekyll site. Private repo, but I can share whatever is helpful.

**Comment by miwebst** [comment] 2020-08-05 22:55
Just as an update, we've investigated this and have a fix but it will take some time to roll this out. I will update this thread when its available!

**Comment by BernhardRode** [comment] 2020-09-01 09:25
It is already nearly a month, since the problem was "fixed". So when will we get the uodated Github action, to work with?

**Comment by miwebst** [comment] 2020-09-01 15:22
This problem has not been fixed yet. The problem isn't actually with the Github Action, its with some downstream components and how they interact with the Github Action. I apologize for the delay, hopefully we will have this fixed in the next 2-3 weeks.

**Comment by BernhardRode** [comment] 2020-09-21 12:37
Already 3 weeks gone again =) Can we help anyhow?

**Comment by miwebst** [comment] 2020-09-21 16:08
Yes we hit a snag in our deployment so its taking an extra week or so. I will make sure to get you an update as soon as I can :)

**Comment by miwebst** [comment] 2020-10-12 18:35
This is fixed now for all newly created Static Web Apps. You may need to delete and recreate your existing app to get this functionality.

**Closed** 2020-11-10 17:32 UTC
