### ISSUE TITLE
Bitbucket - NextJs App deployment to Azure StaticWebApp

### ISSUE THREAD

**Issue by absdhirendra** [Azure/static-web-apps#804] opened 2022-05-16 12:59 UTC
**Not able to deploy NextJS app from bibucket pipeline**
We are using Bitbucket for for one of our NextJs App and there a need to deploy this app to Azure StaticWebApp whenever any change(s) is/are merged to a main branch. Till now we are still exploring to this.

We have created pipeline as per the guidance provided in the link https://www.drware.com/tutorial-publish-azure-static-web-apps-with-bitbucket/ . But still Its not working.

**Expectation**
A clear map/guide/solution to deploy NextJs App from Bitbucket to StaticWebApp

**Comment by annikel** [comment] 2022-05-16 20:08
Hi @absdhirendra, can you provide more details about what exactly is not working? Thank you

**Comment by absdhirendra** [comment] 2022-05-17 08:56
Hi @annikel, Its Bitbucket pipeline setup. We need a map to deploy NextJs App from Bitbucket to StaticWebApp. 

Also Is there anyway so that site can be  deployed manually?

Thank you so much!

**Comment by Reshmi-Sriram** [comment] 2022-05-17 10:00
Hey @absdhirendra, 

A couple of things:
- As of today, Static web Apps only supports deploying Static Next.js websites (work in progress regarding support for hybrid, but no ETA right now)
- If you could share your repo so that we could try repro the same on our end - that should help in resolving the issue.

CC// @rupareddy5-21

**Comment by absdhirendra** [comment] 2022-05-17 10:17
Can you share your email address(s) so that bitbucket repo permission can be granted?

**Comment by rupareddy5-21** [comment] 2022-05-17 10:26
Hi @absdhirendra, This is my email address - rupareddy@microsoft.com

**Comment by absdhirendra** [comment] 2022-05-17 11:15
Have granted the permission, pls check your mail

**Comment by rupareddy5-21** [comment] 2022-07-12 18:23
Hi @absdhirendra sorry for the inconvenience, but the issue is fixed now, you can test it now and please let us know if the issue still persists. Thanks

**Closed** 2023-01-25 18:17 UTC
