### ISSUE TITLE
Moving operation for resource types 'Microsoft.Web/staticSites' across subscriptions or across ResourceGroups failed with InternalServerError 

### ISSUE THREAD

**Issue by dummy-andra** [Azure/static-web-apps#1092] opened 2023-03-06 09:32 UTC
### **Issue Description**
Moving operation for resource types 'Microsoft.Web/staticSites' across subscriptions or across ResourceGroups failed with InternalServerError because it exceeded the allowed time limit of 1 hour.

### **User Role and Permissions**
I am the subscriptions owner, and I also have both Owner and Contributor permissions over the resources. My role management over the Static Web App that I want to move is: contributor, reader, admin, anonymous, authenticated. 

### For Static Web App creation was used

  **Static Web App Deployment Source:**
        - Github
        - Other
        - have not tried using as source AzureDevops
  
  **Static Web App Azure Functions and staging details**
      - Tried with different regions like WestEurope, CentralUS, Est US 2

### **Reproduction Steps**
**Scenario 1:** Move Static Web Site across subscriptions (from subsA to subsB)
**Scenario 2:** Move Static Web Site  across Resource Groups (in another RG, same subscription and region)
**Scenario 3:**  Try  to create Static Web Apps with  Azure Functions and staging details in different regions and try to move then across ResourceGroups in same subscription, or in other subscritions

### Expected Behavior
The Static Web App should be moved successfully without exceeding the allowed time limit.

### Actual Behavior
**In all the scenarios, the move operation failed with an InternalServerError (in Portal log) and with the following message via CLI:**

```
CLI Error Message
Resources '/subscriptions/xxxx/resourceGroups/RG-A/providers/Microsoft.Web/staticSites/demo-static-app' move actions failed. The correlation Id is 'yyyyy'. 
Exception Details: (ResourceMoveTimedOut) Move resources for provider 'Microsoft.Web' did not finish within allowed time '01:00:00'.
- Code: ResourceMoveTimedOut
- Message: Move resources for provider 'Microsoft.Web' did not finish within allowed time '01:00:00'.
- Target: Microsoft.Web/staticSites
```

### Additional Information
Please perform the reproduction steps using the CLI as it provides a more detailed output.

**Comment by dummy-andra** [comment] 2023-03-07 09:29
### **Updates**

**This issue  is on MS side and potentially caused by a change made to the control plane business logic for Static Web Apps.**

### **Action Plan**

Waiting for mitigation from MS side. 

### **Alternative**

Recreate the Static Web App in the desired location, please use CLI (from Portal might be an issue at the moment, see details here: https://github.com/Azure/static-web-apps/issues/1095)

**Comment by cmriachi** [comment] 2023-03-07 23:19
Hi @dummy-andra, yes this was caused by a regression introduced into our Move Resources logic. We are currently rolling out a fix for this. Thank you for your patience.

**Comment by annikel** [comment] 2023-03-09 20:29
Hi @dummy-andra, the fix is now rolled out and you should no longer be experiencing the issue. Thanks

**Closed** 2023-03-09 20:29 UTC
Labels: bug
