### ISSUE TITLE
Error Deploy to SWA

### ISSUE THREAD

**Issue by mrgenesis** [Azure/static-web-apps#149] opened 2020-09-08 21:20 UTC
I did learnt deploy in [Azure Learn](https://docs.microsoft.com/pt-br/learn/modules/create-deploy-static-webapp-gatsby-app-service/). I used [an exemple code](https://github.com/mrgenesis/my-static-web-app) only to understand how working and I used the Learn sandbox environment too. So ultil here allright. Now, I did up to a [new resourse Static Web App](https://docs.microsoft.com/en-us/azure/static-web-apps/get-started-cli?tabs=react) with Azure CLI and with the same as repo used in Azure Learn sandbox, but didn't working. I think that the error diplayed is cased per something in [azure_static_web_apps_api_token](https://github.com/mrgenesis/my-static-web-app/blob/efe332588178df11bf3a5640ddae9a56c1ebd26a/.github/workflows/azure-static-web-apps-red-bay-069ec1910.yml#L25), but I don't found where get it. Can someone help me please?

![image](https://user-images.githubusercontent.com/32000025/92527401-f0a6d100-f1f4-11ea-87fe-9def70fb3a41.png)

**Comment by mrgenesis** [comment] 2020-09-08 22:07
I found the answer in [this link](https://github.com/Azure/static-web-apps/issues/130#issuecomment-689160782). Thank you.

**Comment by miwebst** [comment] 2020-09-10 18:11
Closing this as its a duplicate of #130. Keeping that open for tracking purposes.

**Closed by miwebst** 2020-09-10 18:11 UTC
