### ISSUE TITLE
Pipe skipped after `Downloaded newer image for staticwebapps.azurecr.io/bitbucket-deploy:stable`

### ISSUE THREAD

**Issue by yt11sf** [Azure/static-web-apps#1366] opened 2023-12-05 23:32 UTC
**Describe the bug**
Since December 4th 2023, 4:08:04 pm CST, the pipe skipped all steps after `Status: Downloaded newer image for staticwebapps.azurecr.io/bitbucket-deploy:stable` in Bitbucket.

**To Reproduce**
1. Create a bitbucket-pipelines.yml to deploy the static web app using Bitbucket pipeline
    ```
    image: atlassian/default-image:3
    definitions:
    services:
        docker:
        memory: 4096

    pipelines:
    branches:
        release:
        - step:
            name: Deploy staging to Azure
            service: docker
            size: 2x
            deployment: release
            script:
                - chown -R 165536:165536 $BITBUCKET_CLONE_DIR
                - pipe: microsoft/azure-static-web-apps-deploy:main
                variables:
                    APP_LOCATION: '$BITBUCKET_CLONE_DIR'
                    OUTPUT_LOCATION: '$BITBUCKET_CLONE_DIR/dist/fulfillment'
                    API_TOKEN: $API_TOKEN
                    APP_BUILD_COMMAND: npm run build-release
                    DEVELOPMENT_ENVIRONMENT: release
                    VERBOSE: 'true'
    ```
2. Push the code to release branch and let the pipeline run.

**Expected behavior**
The pipeline should return deployment id, build the app with Oryx, then deploy the app.

**Comment by DjilanMouhous** [comment] 2023-12-06 06:55
Same here. Starting to think about moving to GitHub 😬

**Comment by vladpani** [comment] 2023-12-06 11:23
This impacts our company as well.
Can't deploy Static Web Apps and manual deployment can't reuse the same resource due to the source lock.

**Comment by marcuhrich** [comment] 2023-12-06 14:03
This stopped working yesterday for our static web app deployment too. Hoping there is a fix or workaround available soon.

**Comment by federicomazzalovo** [comment] 2023-12-06 14:03
Same problem here...

**Comment by marco-bertelli** [comment] 2023-12-06 14:08
same here

**Comment by alessandro-casonato-gsm** [comment] 2023-12-06 14:12
I can feel you, same problem here

**Comment by Domi-Vogell** [comment] 2023-12-06 14:15
Same here. Please comment here if you find a workaround other than switching away from bitbucket.

**Comment by hey-cwuerzlhuber** [comment] 2023-12-06 14:16
Same here. Was searching for the problem for quite some time until I recognised, the issue is not on my end.
Weird thing is, the pipeline ends with success, but no deployment to azure is happening.

**Comment by DidiDerDenker** [comment] 2023-12-06 14:38
Same problem here

**Comment by blagovest-doshkov** [comment] 2023-12-06 16:10
Hello all,

We've found a workaround using "[SWA CLI](https://azure.github.io/static-web-apps-cli/)".
We are using BitBucket pipeline as well. So, instead using the mentioned pipe "microsoft/azure-static-web-apps-deploy:main" we are installing the swa cli and calling the "deploy" command.

```
- npm install -g @azure/static-web-apps-cli
- swa --verbose=silly deploy "$BITBUCKET_CLONE_DIR/<app-folder>" --deployment-token=$deployment_token --env=production
```
@yt11sf for your case you should look up into the CLI commands to configure your app.

I'm also adding sample of our yml file which is working atm.

```
image: atlassian/default-image:3
image: node:20.10.0

pipelines:   
  branches: #For automatic trigger after push to branch
    pipeline_fix: #For automatic trigger after push to Dev
    - step: 
        name: Automatic Build and Deploy to pipeline_fix
        caches:
            - node
        deployment: Dev
        script:
            - cd AngularApp

            # Configuring App Settings
            # <Hidden Not Important>

            - npm install @angular/cli -g
            - npm install

            #production configuration actually holds the variable names of the Bibucket deployment variables
            - ng build --configuration=production
          
            - npm install -g @azure/static-web-apps-cli    
            - swa --verbose=silly deploy "$BITBUCKET_CLONE_DIR/AngularApp/dist/AngularApp" --deployment-token=$deployment_token --env=production
```
Hope this will help you, guys! :)

**Comment by loreleim** [comment] 2023-12-06 20:14
Can confirm @blagovest-doshkov 's fix worked for deploying a React Web App to an Azure Static Web App instance.

Broken script / pipeline build as of the update yesterday
```
script:
          - npm install
          - npm run build
          - pipe: microsoft/azure-static-web-apps-deploy:main
            variables:
                APP_LOCATION: '$BITBUCKET_CLONE_DIR/build'
                OUTPUT_LOCATION: './'
                API_TOKEN: $deployment_token
```

Working + modified for our React Static Web App
```
script:
          - npm install
          - npm install -g @azure/static-web-apps-cli
          - npm run build
          - swa --verbose=silly deploy "$BITBUCKET_CLONE_DIR/build" --deployment-token=$deployment_token --env=production
   
```

**Comment by yt11sf** [comment] 2023-12-06 22:53
@blagovest-doshkov I have been trying to deploy using your work around for hours. The log says the project is deployed, but the web app did not reflect the changes.

The pipeline:
```
pipelines:
  branches:
    release:
      - step:
          name: Deploy staging to Azure
          caches:
            - node
          deployment: release
          script:
            - npm install
            - ng build --configuration=release
            # swa is available in image, and therefore no need to install. 
            - swa --verbose=silly deploy $BITBUCKET_CLONE_DIR/dist/fulfillment --deployment-token=$API_TOKEN --env=release
```

Bitbucket pipeline log:
```
swa --verbose=silly deploy $BITBUCKET_CLONE_DIR/dist/fulfillment --deployment-token=$API_TOKEN --env=release
Welcome to Azure Static Web Apps CLI (1.1.6)
Getting config file options from "swa-cli.config.json"...
Config file does not exist at "swa-cli.config.json"
Resolving outputLocation=/opt/atlassian/pipelines/agent/build/dist/fulfillment full path...
Deploying front-end files from folder:
/opt/atlassian/pipelines/agent/build/dist/fulfillment
Consider providing api-language and version using --api-language and --api-version flags,
otherwise default values apiLanguage: node and apiVersion: 16 will apply
Deployment token provided via flag
--deployment-token:
Deploying to environment: release
Trying to read workflow config with values:
appLocation: /opt/atlassian/pipelines/agent/build
outputLocation: /opt/atlassian/pipelines/agent/build/dist/fulfillment
apiLocation:
dataApiLocation:
No workflow config folder found at /opt/atlassian/pipelines/agent/build/.github/workflows
Validating user workflow config (BEFORE):
appLocation: /opt/atlassian/pipelines/agent/build
outputLocation: /opt/atlassian/pipelines/agent/build/dist/fulfillment
apiLocation:
dataApiLocation:
Validating user workflow config (AFTER):
appLocation: /opt/atlassian/pipelines/agent/build
apiLocation:
outputLocation: /opt/atlassian/pipelines/agent/build/dist/fulfillment
dataApiLocation:
No staticwebapp.config.json found in current project
Deploying project to Azure Static Web Apps...
Could not find StaticSitesClient local binary
Fetching release metadata for version: stable. Please wait...
version: stable
buildId: 1.0.025241
publishDate: 2023-11-30T02:51:40.8356813Z
files:
linux-x64:
url: https://swalocaldeploy.azureedge.net/downloads/1.0.025241/linux/StaticSitesClient
sha: e4ccb44c516e03e6dcc2a26a35ffd4c84a61dfea581990dd5c0edb7c12662db0
win-x64:
url: https://swalocaldeploy.azureedge.net/downloads/1.0.025241/windows/StaticSitesClient.exe
sha: 4146ac01a488910d6ea066e1c46505048b0c9af2e74ef273c4236b387796712d
osx-x64:
url: https://swalocaldeploy.azureedge.net/downloads/1.0.025241/macOS/StaticSitesClient
sha: 05b213d7861454368d2c9801b0ccc75cfd13cb48f8e121fffaa2ab7e9b5671cd
Downloading https://swalocaldeploy.azureedge.net/downloads/1.0.025241/linux/StaticSitesClient@1.0.025241
[swa] ✔ Downloading https://swalocaldeploy.azureedge.net/downloads/1.0.025241/linux/StaticSitesClient@1.0.025241
Checksum match: e4ccb44c516e03e6dcc2a26a35ffd4c84a61dfea581990dd5c0edb7c12662db0
Saved binary to /root/.swa/deploy/1.0.025241/StaticSitesClient
Saved metadata to /root/.swa/deploy/StaticSitesClient.json
Deploying using /root/.swa/deploy/1.0.025241/StaticSitesClient@1.0.025241
Deploying using the following options:
env:
SWA_CLI_DEBUG: silly
SWA_RUNTIME_WORKFLOW_LOCATION:
SWA_RUNTIME_CONFIG_LOCATION:
SWA_RUNTIME_CONFIG:
SWA_CLI_VERSION: 1.1.6
SWA_CLI_DEPLOY_DRY_RUN: false
SWA_CLI_DEPLOY_BINARY: /root/.swa/deploy/1.0.025241/StaticSitesClient@1.0.025241
DEPLOYMENT_ACTION: upload
DEPLOYMENT_PROVIDER: SwaCli
REPOSITORY_BASE: /opt/atlassian/pipelines/agent/build
SKIP_APP_BUILD: true
SKIP_API_BUILD: true
DEPLOYMENT_TOKEN:
APP_LOCATION: /opt/atlassian/pipelines/agent/build/dist/fulfillment
API_LOCATION:
DATA_API_LOCATION:
CONFIG_FILE_LOCATION:
VERBOSE: true
FUNCTION_LANGUAGE: node
FUNCTION_LANGUAGE_VERSION: 16
DEPLOYMENT_ENVIRONMENT: release
Preparing deployment. Please wait...
ℹ DeploymentId: [redacted deployment id]
ℹ Preparing deployment. Please wait...
ℹ Verbose logging enabled
ℹ Try to validate location at: '/opt/atlassian/pipelines/agent/build/opt/atlassian/pipelines/agent/build/dist/fulfillment'.
ℹ Build timeout not specified, defaulting to 15 minutes
ℹ App Directory Location: '/opt/atlassian/pipelines/agent/build/dist/fulfillment' was found.
ℹ Try to validate location at: '/opt/atlassian/pipelines/agent/build/swa-db-connections'.
ℹ Looking for event info
ℹ Event info parsed from action options.
ℹ Could not get repository branch. Proceeding
ℹ Could not get repository url. Proceeding
ℹ Skipping step to build /opt/atlassian/pipelines/agent/build/dist/fulfillment with Oryx
ℹ Could not find staticwebapp.config.json file.
ℹ Didn't find Oryx manifest file under location: /opt/atlassian/pipelines/agent/build/[redacted deployment id]-swa-oryx/app-manifest/oryx-manifest.toml
ℹ Determined default file to be: index.html
ℹ Calculating the size of app artifacts: 11153574 B
ℹ No Api directory specified. Azure Functions will not be created.
ℹ Either no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.
ℹ Zipping App Artifacts
ℹ App Zip will be created from directory: /opt/atlassian/pipelines/agent/build/dist/fulfillment
ℹ Done Zipping App Artifacts
ℹ Uploading build artifacts.
ℹ Skipping function upload as functions are identical to last successful deployment.
ℹ Finished Upload. Polling on deployment.
ℹ Status: InProgress. Time: 0.0276102(s)
ℹ Status: Succeeded. Time: 15.0571447(s)
ℹ Deployment Complete :)
ℹ Thanks for using Azure Static Web Apps!
✔ Project deployed to https://[redacted].azurestaticapps.net 🚀
```
Am I doing something wrong?

**Comment by loreleim** [comment] 2023-12-06 23:07
@yt11sf I think the --env flag needs to reflect your env naming in Azure. in Settings > Configurations. By default in Azure x Bitbucket connections there's only a Production branch. Github can utilize the staging envs.

this
```
swa --verbose=silly deploy $BITBUCKET_CLONE_DIR/dist/fulfillment --deployment-token=$API_TOKEN --env=release
```

might need to change to 
```
swa --verbose=silly deploy $BITBUCKET_CLONE_DIR/dist/fulfillment --deployment-token=$API_TOKEN --env=production
```

**Comment by Josh-Grafman** [comment] 2023-12-08 18:57
@blagovest-doshkov thanks for the save

**Comment by Josh-Grafman** [comment] 2023-12-08 20:31
@blagovest-doshkov Thanks for the save. Had some annoyance trying to get this to work in our base Alpine image, ended up just using the node:20.10.0 for the deploy step to avoid the hassle. Other than that, worked like a charm. It's honestly faster than the pipe was.

**Comment by thomasgauvin** [comment] 2023-12-11 22:35
Hi folks, we investigated this & detected a bug in our most recent deployment of the microsoft/azure-static-web-apps-deploy pipe. We've since fixed this and the fix is live now. Please let us know if this resolves your issue to confirm

**Comment by sviluppo-mytec** [comment] 2023-12-12 07:45
@thomasgauvin It's working for me
Thanks for the fix

**Comment by thomasgauvin** [comment] 2023-12-12 15:25
Excellent, thanks for confirming @sviluppo-mytec, closing this issue & feel free to reopen if you believe this issue is still present

**Closed by thomasgauvin** 2023-12-12 15:25 UTC

**Comment by usererror0** [comment] 2024-02-28 03:30
Seeing this exact same issue. Could it have returned? Is anyone able to confirm or deny? 

I was able to deploy with swa cli but my bitbucket pipe skips after Status: Downloaded newer image for [staticwebapps.azurecr.io/bitbucket-deploy:stable](http://staticwebapps.azurecr.io/bitbucket-deploy:stable). I also see this in the docker logs: `level=error msg="Handler for POST /v1.41/containers/create returned error: No such image: [staticwebapps.azurecr.io/bitbucket-deploy:stable](http://staticwebapps.azurecr.io/bitbucket-deploy:stable)"`

**Comment by sviluppo-mytec** [comment] 2024-02-28 08:36
I confirm the issue reported by @usererror0 
The last line in the log is
Status: Downloaded newer image for [staticwebapps.azurecr.io/bitbucket-deploy:stable](http://staticwebapps.azurecr.io/bitbucket-deploy:stable)

While when the deployment works it continues with
DeploymentId: xxxxx-xxxxx-xxxxx-xxxx
Try to validate location at: '/bin/staticsites/opt/atlassian/pipelines/agent/build/publish/wwwroot'.
App Directory Location: '/opt/atlassian/pipelines/agent/build/publish/wwwroot' was found.
Try to validate location at: '/bin/staticsites/swa-db-connections'.

until

Deployment Complete :)
Visit your site at: https://xxxxx.azurestaticapps.net/
Thanks for using Azure Static Web Apps!
Exiting

**Comment by thclaes** [comment] 2024-02-28 10:39
Same here

**Comment by thclaes** [comment] 2024-02-29 08:47
Works again, as mentioned in this issue:
https://github.com/Azure/static-web-apps/issues/1422
