### ISSUE TITLE
React quickstart doesn't build

### ISSUE THREAD

**Issue by olitomlinson** [Azure/static-web-apps#1184] opened 2023-05-28 08:47 UTC
You need to update `react-scripts` from `3.4.0` to `^5.0.1`

https://github.com/staticwebdev/react-basic/blob/c734efc069399e0e7879c0c385f86b29237fa466/package.json#L11

Otherwise you get this error on build :

`{
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}`

**Comment by thomasgauvin** [comment] 2023-05-31 14:21
@olitomlinson thanks for reporting this, however, I'm not able to reproduce this error as you can see from this successful build: https://github.com/thomasgauvin/swa-react-basic/actions/runs/5133997577. Can you share logs/errors so we can investigate if something else is at play?

**Comment by olitomlinson** [comment] 2023-05-31 22:12
Sorry, I mean't to say it doesn't build locally on my dev environment.

@thomasgauvin 

**Repro steps** 

- clone repo
- `npm install`
- `npm run build`

```
react-basic % npm run build

> hello@0.1.0 build
> react-scripts build

Creating an optimized production build...
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/olivertomlinson/Desktop/dev/react-basic/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/olivertomlinson/Desktop/dev/react-basic/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/olivertomlinson/Desktop/dev/react-basic/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/olivertomlinson/Desktop/dev/react-basic/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/olivertomlinson/Desktop/dev/react-basic/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/olivertomlinson/Desktop/dev/react-basic/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/olivertomlinson/Desktop/dev/react-basic/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/olivertomlinson/Desktop/dev/react-basic/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/Users/olivertomlinson/Desktop/dev/react-basic/node_modules/react-scripts/scripts/build.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/olivertomlinson/Desktop/dev/react-basic/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/olivertomlinson/Desktop/dev/react-basic/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/olivertomlinson/Desktop/dev/react-basic/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/olivertomlinson/Desktop/dev/react-basic/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/olivertomlinson/Desktop/dev/react-basic/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/olivertomlinson/Desktop/dev/react-basic/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/olivertomlinson/Desktop/dev/react-basic/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/olivertomlinson/Desktop/dev/react-basic/node_modules/babel-loader/lib/index.js:55:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by twitthoeft-gls** [comment] 2024-02-13 21:14
+1
Just had the same issue.  Fresh clone of https://github.com/staticwebdev/react-basic
Ran npm install.  Then ran npm run build with the same issue: `ERR_OSSL_EVP_UNSUPPORTED`

Editing the package.json and updating "react-scripts": "5.0.1" fixed it.  Thanks, @olitomlinson 🎉

**Comment by thomasgauvin** [comment] 2024-02-14 19:15
Hi everyone, thanks for notifying us and detailing the repro steps, I've updated the template so it builds and runs without issues based on your recommended fix https://github.com/staticwebdev/react-basic/commit/be9a2ae9d8d59b28948b50952668924e124611bd

**Comment by thomasgauvin** [comment] 2024-02-14 19:15
Closing this thread as resolved, please let me know if this needs to be reopened

**Closed by thomasgauvin** 2024-02-14 19:15 UTC
