### ISSUE TITLE
add custom domain button is disabled

### ISSUE THREAD

**Issue by matcha440** [Azure/static-web-apps#115] opened 2020-08-07 02:12 UTC
I am currently unable to complete setup of a custom domain.  The add button shows here as disabled.
![image](https://user-images.githubusercontent.com/13713268/89601101-afa45100-d831-11ea-927e-84181e4e0b88.png)

Is there a reason this button is currently disabled?

**Comment by matcha440** [comment] 2020-08-07 14:52
FYI, I found a workaround for this by using Azure CLI.  Here's the command that worked for me.  So if anyone else runs into this issue, I hope it helps them out too.

```
az staticwebapp hostname set --hostname www.example.com --name MyStaticWebApp
```

https://docs.microsoft.com/en-us/cli/azure/staticwebapp/hostname?view=azure-cli-latest#az-staticwebapp-hostname-set

**Comment by HaykSahakyan** [comment] 2020-08-08 09:24
I'm facing the same problem.

**Comment by HaykSahakyan** [comment] 2020-08-08 18:17
> FYI, I found a workaround for this by using Azure CLI. Here's the command that worked for me. So if anyone else runs into this issue, I hope it helps them out too.
> 
> ```
> az staticwebapp hostname set --hostname www.example.com --name MyStaticWebApp
> ```
> 
> https://docs.microsoft.com/en-us/cli/azure/staticwebapp/hostname?view=azure-cli-latest#az-staticwebapp-hostname-set

I', getting an error: "CNAMERecord is invalid.  Please ensure the CNAME record has been created."

**Comment by matcha440** [comment] 2020-08-08 20:38
> 
> 
> > FYI, I found a workaround for this by using Azure CLI. Here's the command that worked for me. So if anyone else runs into this issue, I hope it helps them out too.
> > ```
> > az staticwebapp hostname set --hostname www.example.com --name MyStaticWebApp
> > ```
> > 
> > 
> > https://docs.microsoft.com/en-us/cli/azure/staticwebapp/hostname?view=azure-cli-latest#az-staticwebapp-hostname-set
> 
> I'm getting an error: "CNAMERecord is invalid. Please ensure the CNAME record has been created."

Do you have your domain setup as a CNAME to your static web app's address yet?  You have to be sure you do that first, and then give it time to propagate through DNS.  If not, then yeah this won't work.

**Comment by HaykSahakyan** [comment] 2020-08-09 05:06
> > > FYI, I found a workaround for this by using Azure CLI. Here's the command that worked for me. So if anyone else runs into this issue, I hope it helps them out too.
> > > ```
> > > az staticwebapp hostname set --hostname www.example.com --name MyStaticWebApp
> > > ```
> > > 
> > > 
> > > https://docs.microsoft.com/en-us/cli/azure/staticwebapp/hostname?view=azure-cli-latest#az-staticwebapp-hostname-set
> > 
> > 
> > I'm getting an error: "CNAMERecord is invalid. Please ensure the CNAME record has been created."
> 
> Do you have your domain setup in your DNS zone as a CNAME to your static web app's address yet? You have to be sure you do that first, and then give it time to propagate through DNS. If not, then yeah this won't work.

Thank you! CNAME was configured (CloudFlare) but I figured out that the problem was that record was "proxied". So I switched it to "DNS only" for a moment to make it visible to Azure and successfully added my custom domain name. I can see it in Azure console and my static web app is accessible with that custom domain name.
BUT.
When I'm switching that CNAME record back to "Proxied"  I'm getting "Error code: SSL_ERROR_NO_CYPHER_OVERLAP"
in browser. Does it means that I should keep that CNAME record in CloudFlare as "DNS only"? For me this is unacceptable.
SSL mode in CloudFlare is set to "Full".

**Comment by HaykSahakyan** [comment] 2020-08-09 06:09
FYI, The problem was on CloudFlare's side.

Cloudflare SSL only applies up to first level subdomains. For example, you might not be seeing any errors on the root domain (yoursite.com) and www (www.yoursite.com) over https://, but get errors on second level subdomains (test.www.yoursite.com). This can be fixed with a Cloudflare Dedicated Certificate with Custom Hostnames.

For example:

blog.yourdomain.com would be fine (one level)
travel.blog.yourdomain.com would not work (two levels)"

**Comment by dcollien** [comment] 2020-08-10 07:23
Unfortunately, trying the workaround (CLI) only gives me `Operation returned an invalid status code 'Conflict'`

**Comment by dcollien** [comment] 2020-08-10 07:36
I noticed the title on the button says, "Reached maximum custom domains for a Free Static Web App. " which is very odd, since I just deleted the domain from another one to add it to this one...

**Comment by HaykSahakyan** [comment] 2020-08-10 07:46
> I noticed the title on the button says, "Reached maximum custom domains for a Free Static Web App. " which is very odd, since I just deleted the domain from another one to add it to this one...

Didn't even know that there such a limit, is there any official docs about that?
Anyhow in my case, I was going to add my very first custom domain but "Add" button was disabled.

**Comment by dcollien** [comment] 2020-08-10 07:53
That's the first I've seen it too.

I finally managed to get mine working via the CLI, here's a limerick:

There once was a limit on domains
That was giving developers pains
It was eventually consistent,
So you had to be persistent
'til the CLI no longer complains

**Comment by miwebst** [comment] 2020-08-10 15:44
There has always been a limit of 1 custom domain per Free Static Web App resource. The button being disabled is a regression in the Portal that we are working to fix.

**Comment by HaykSahakyan** [comment] 2020-08-10 15:50
> There has always been a limit of 1 custom domain per Free Static Web App resource. The button being disabled is a regression in the Portal that we are working to fix.

Thanks! How should I make Static Web App paid resource to overcome that limit?

**Comment by miwebst** [comment] 2020-08-10 16:12
We only have the free sku today :) do you have a scenario when you need more than 1 custom domain for a single static web app?

**Comment by HaykSahakyan** [comment] 2020-08-10 16:16
> We only have the free sku today :) do you have a scenario when you need more than 1 custom domain for a single static web app?

There is no such scenario at this moment :) Just because you mentioned "Free" I decided to clarify :) Thank you!

**Comment by miwebst** [comment] 2020-08-10 16:58
This should be fixed now in the Portal. Sorry for the inconvenience!

**Closed** 2020-08-11 17:34 UTC
