### ISSUE TITLE
Receiving 401 from managed function app in centralus region only

### ISSUE THREAD

**Issue by ramseytm** [Azure/static-web-apps#1169] opened 2023-05-19 18:20 UTC
**Recieving a 401 when function has AuthorizationLevel.Function applied**

We have a static web app application that utilizes a managed function app. Starting this morning (not entirely sure when but it appears to have been around 7AM Eastern) all of our centralus region static web app instances began returning 401 responses for any requests made to our /api endpoints. This doesn't appear to be occurring in our eastus2 locations and no code was deployed or changed preceding the errors. To mitigate the issue we starting routing all traffic through our eastus2 static web app resource via front door which seems to be working but our centralus resources are still experiencing the same issue going on 7 hours now.

I tested things out in one of our test environments in the centralus region and it appears that updating the authorization level for the http trigger functions in our managed function app to be Anonymous instead of Function appears to clear up the 401 responses. 

These functions have been set to AuthorizationLevel.Function for over a year and haven't changed so we're not sure why this behavior appears to have changed this morning in one region only. I was hoping to confirm that AuthorizationLevel.Function is correct and supported by managed functions within an SWA and this might just be due to an Azure outage versus something we're doing incorrectly. I assume that's the case as AuthorizationLevel.Function is working in our eastus2 instances and like I said we haven't modified that setting is some time.

**Comment by pwang2** [comment] 2023-05-20 14:03
same thing happened to deployed APP which previously worked.  

Also, the new 1.1.2 SWA cli is super buggy too which makes a frustrated diagnosis expensive.

**Comment by jwoytas** [comment] 2023-05-21 06:43
Experiencing this issue as well.  Redeployed the swa from centralus to westus2 and had the same issue.  Only updating the authorization level for the trigger from Function to Anonymous seemed to help.

**Comment by TroyWitthoeft** [comment] 2023-05-22 13:11
Similar thing happened to us. 

Starting at Thursday 05/18 midnight EST, multiple static web apps with managed apis (c#, func v4, .net 6.0)  began reporting 401 unauthorized.   Start/stop did not fix.  Redeploy did not fix.  Hot to hotfix all apis by changing auth level from `AuthorizationLevel.Function` to `AuthorizationLevel.Anonymous`. 

This incident seems to have impacted multiple customers.  Do we know if this was an isolated incident? Any root cause?  Can we set functions back to `AuthorizationLevel.Function` ?

**Comment by TroyWitthoeft** [comment] 2023-05-23 20:18
@ramseytm - I don't think this was region related?  We saw the same thing as @jwoytas, the issue remained regardless of region.

**Comment by pwang2** [comment] 2023-05-24 16:23
any RCA for this?  shall we keep AuthorizationLevel to Anonymous?

**Comment by jorgesanchezh** [comment] 2023-05-24 21:43
Similar issue here. Receiving 401 from managed function app since last week.

**Comment by ryanbyk** [comment] 2023-05-28 20:54
Same issue, in west us 2.  I have tried implementing the bring your own functions as a means to fix it and no luck there either.

**Comment by ramseytm** [comment] 2023-05-31 16:03
Whatever the change of behavior is, it appears to have been deployed to the EastUS2 region this morning. We're opening a ticket directly with Microsoft to see if we can get any answer on what change is occurring and get documentation on the supported cases for function key's in a static web app resource.

**Comment by danbasszeti** [comment] 2023-05-31 17:11
This has just affected us today in production, very frustrating.

**Comment by vivekjilla** [comment] 2023-06-01 05:03
Hi everyone. We're following up with Functions team to see if something regressed there. Meanwhile you can set the AuthorizationLevel to Anonymous to get unblocked. It's safe to set the AuthorizationLevel as Anonymous, as we have another layer of authorization checks in place so that only SWA can access the managed function endpoints.

**Comment by vivekjilla** [comment] 2023-06-01 06:35
Can I also get some details like the static web app name/url of the impacted sites. And if redeploying the app is resolving the issue, to understand the issue better. Thanks!

**Comment by danbasszeti** [comment] 2023-06-01 07:45
> Hi everyone. Apologies for the inconvenience! We're following up with Functions team to see if something regressed there.
> 
> Meanwhile you can set the AuthorizationLevel to Anonymous for your functions to get unblocked. It's safe to set the AuthorizationLevel as Anonymous, as we have another layer of authorization checks in place so that only SWA can access the managed function endpoints.

What about bring your own function endpoints, are they safe to be anonymous? 

I've already fixed my sites by switching them to anonymous so not sure they will be much help.

**Comment by turdwaster** [comment] 2023-06-01 07:46
Can confirm that
- Redeploying by itself does not help
- Redeploying with AuthorizationLevel.Anonymous fixes the problem
- This currently affects western europe

**Comment by paulgravesnewday** [comment] 2023-06-01 09:53
This is also affecting our Azure Static Web App with a managed function. As far as I know it's not possible to change the Auth level on a managed function app so the workaround doesn't work for our use case.

**Comment by msitsoftware** [comment] 2023-06-01 11:06
Workaround (AuthLevel='anonymous') works fine for me as well

**Comment by vivekjilla** [comment] 2023-06-01 12:45
@danbasszeti Yes, it's safe for BYOF as well. 

@paulgravesnewday You can set `"authLevel": "anonymous"` in your function.json. For [reference](https://github.com/staticwebdev/vanilla-api/blob/main/api/GetMessage/function.json#LL4C4-L4C32)

**Comment by FrankBurmo** [comment] 2023-06-01 19:28
My site is also down because of this. Western Europe.

Do you have an ETA for the fix?

**Comment by TroyWitthoeft** [comment] 2023-06-02 05:31
Redeploy and start/stop did not fix.  Only changing auth level was a fix.

**Comment by ulfbrehmer** [comment] 2023-06-02 07:43
My Azure SWA APIs in West Europe started to get 401s 2023-06-01 11:30 CEST and are still failing, 22 hours later. I haven't tried switching to anonymous yet (reluctant to do this).

**Comment by niklashaetty** [comment] 2023-06-02 16:50
@vivekjilla Sorry, what other layers of authorization are in place to secure the managed functions endpoints? Setting the authorization level to anonymous will allow anyone to access the managed functions endpoints without providing any form of credentials, right?

**Comment by vivekjilla** [comment] 2023-06-02 17:06
@niklashaetty what you said is true for standalone function apps. But for function apps managed by/linked to SWA,  we restrict the traffic to go only via SWA and disable direct access by default. 

@ramseytm Thanks for sharing the update here!

**Comment by mikkark** [comment] 2023-06-03 12:07
I got this issue as well in my SWA's. All my API endpoints are publicly accessible though. I was surprised to realize that indeed I had some Azure Functions with authlevel: function. They have been like this for two years now.

I don't really understand how or why authlevel: function has ever worked. This has to be something specific to SWA instead of e.g. the good old Azure App Service.

If I understood correctly, there is a fix on its way that will again enable authlevel: function API endpoints.

My question is: shouldn't those be set as authlevel: anonymous in the first place? Shouldn't authlevel: function always require the key in the URL to be able to access the endpoint?

**Comment by TroyWitthoeft** [comment] 2023-06-03 13:20
@mikkark - I have had the same experience.  We have a swas with managed functions and all of their api endpoints are publicly accessibly.  

I'd really like an answer from MS on this.  Are manged api endpoint supposed to be publicly accessible?  I actually need them to be, but I have folks saying they shouldn't be?

**Comment by vivekjilla** [comment] 2023-06-03 14:40
@mikkark, @TroyWitthoeft sorry for the confusion. There are two parts here for managed functions.
1. API request going to SWA endpoint: Yes, these will be publicly accessible unless you define [SWA auth roles](https://learn.microsoft.com/en-us/azure/static-web-apps/configuration#routes) to restrict access.
2. Managed function is also an azure function managed by SWA: If someone gets access to that managed function name and tries to access it directly, we restrict that access. 
 
So end user has to call your SWA endpoint to access the APIs. And SWA passes the necessary auth info when forwarding the request to managed function. This is all abstracted out to SWA users.

The regression here is, the auth flow between SWA and managed function had an issue and so we observed 401s.

Update: This issue has been now resolved. So, using authLevel: function should also work. But it's not strictly needed, as we have second layer of checks in place to handle the 2nd point above.

Hope this helps! Apologies for the confusion and inconvenience.

**Comment by DessNotFound** [comment] 2023-06-05 09:29
I'm still experiencing this issue with my managed functions even after redeployment, this issue started to occur last Wednesday.

**Comment by vivekjilla** [comment] 2023-06-05 09:40
Apologies for this. @DessNotFound Issue resolution in progress for Node/Python functions. Resolved for Dotnet functions. 
Will update once it's fixed completely. Meanwhile you can use the workaround mentioned above. Thanks!

**Comment by DessNotFound** [comment] 2023-06-05 10:57
Thank you for such a fast response! Do you have an estimate on when the issue will be resolved?

**Comment by vivekjilla** [comment] 2023-06-06 02:19
We're working on rolling out the fix gradually, now. Current estimated ETA is 12 hours.

**Comment by vivekjilla** [comment] 2023-06-06 06:49
The fix has been rolled out to Node and Python apps as well and the issue should be mitigated now. In case someone is still seeing this issue, redeployment should resolve the issue. Apologies for the inconvenience.

**Closed by vivekjilla** 2023-06-06 06:49 UTC

**Comment by woutervs** [comment] 2023-12-21 02:17
Has this actually been resolved for dotnet? Currently have a .net 8 isolated function deployed that works with SWA SPA only when the AuthorizationLevel is set to Anonymous.

**Comment by itpropro** [comment] 2024-03-02 19:07
> Has this actually been resolved for dotnet? Currently have a .net 8 isolated function deployed that works with SWA SPA only when the AuthorizationLevel is set to Anonymous.

This is normal behavior according to the Static Web Apps docs. If the authorization of the functions require a function key, you need to provide it or put the function to anonymous: https://learn.microsoft.com/en-us/azure/static-web-apps/functions-bring-your-own#security-constraints
