### ISSUE TITLE
Difficulty building an Angular app with SWA

### ISSUE THREAD

**Issue by SeanKilleen** [Azure/static-web-apps#118] opened 2020-08-10 02:06 UTC
I'm working to build an angular web app and I'm having some trouble publishing with Azure Static Web apps. It appears based on my build logs that something strange happens when setting up php-composer, and it never finishes. This makes me think it might not be my app, but potentially could be my configuration causing the isuse.

My source code lives at `./src` and the output ends up in `./src/dist/skillustrator-frontend`

## Narrowing it down

✅ I was able to deploy an early version of the app, which was done in React, to Azure SWA
✅ I can publish the current Angular version using Netlify, so I don't think it's an issue with dependencies, `package.json`, etc.

## Files 
Actions config:

```yaml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview # is this still the right version? I only see one release.
        with:
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_SAND_042DA7C0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/src" # App source code path
          app_artifact_location: "dist/skillustrator-frontend" # relative to the src directory? Or do I need to include that?
          app_build_command: 'npm run build-prod' #note: this calls 'ng build --prod`
          
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_SAND_042DA7C0F }}
          action: "close"
```

Output from a failure -- note that it looks like the there's no `done`:

```
2020-08-10T01:48:56.8223254Z ##[group]Run Azure/static-web-apps-deploy@v0.0.1-preview
2020-08-10T01:48:56.8223425Z with:
2020-08-10T01:48:56.8224310Z   azure_static_web_apps_api_token: ***
2020-08-10T01:48:56.8224956Z   repo_token: ***
2020-08-10T01:48:56.8225075Z   action: upload
2020-08-10T01:48:56.8225179Z   app_location: /src
2020-08-10T01:48:56.8225288Z   app_artifact_location: dist/skillustrator-frontend
2020-08-10T01:48:56.8225402Z   app_build_command: npm run build-prod
2020-08-10T01:48:56.8225510Z ##[endgroup]
2020-08-10T01:48:56.8250472Z ##[command]/usr/bin/docker run --name cb8a3ef0455b254e88846ba8bb230edeea_79bb3e --label 8118cb --workdir /github/workspace --rm -e INPUT_AZURE_STATIC_WEB_APPS_API_TOKEN -e INPUT_REPO_TOKEN -e INPUT_ACTION -e INPUT_APP_LOCATION -e INPUT_APP_ARTIFACT_LOCATION -e INPUT_APP_BUILD_COMMAND -e INPUT_API_BUILD_COMMAND -e INPUT_API_LOCATION -e INPUT_ROUTES_LOCATION -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/skillustrator-frontend/skillustrator-frontend":"/github/workspace" 8118cb:8a3ef0455b254e88846ba8bb230edeea
2020-08-10T01:48:57.4345739Z DeploymentId: d4c73d91-3c0e-4731-8f15-f933c072339f
2020-08-10T01:48:57.4346058Z 
2020-08-10T01:48:57.5474391Z App Directory Location: '/src' was found.
2020-08-10T01:48:57.5478111Z No Api directory specified. Azure Functions will not be created.
2020-08-10T01:48:58.0731975Z Starting to build app with Oryx
2020-08-10T01:48:58.0732841Z Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
2020-08-10T01:48:58.0733242Z Oryx will build app with the following custom override command: npm run build-prod
2020-08-10T01:48:58.0733519Z ---Oryx build logs---
2020-08-10T01:48:58.0733748Z 
2020-08-10T01:48:58.0733969Z 
2020-08-10T01:48:58.5875158Z Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
2020-08-10T01:48:58.5877795Z You can report issues at https://github.com/Microsoft/Oryx/issues
2020-08-10T01:48:58.5879070Z 
2020-08-10T01:48:58.5881308Z Oryx Version: 0.2.20200719.1, Commit: 80603ef82312ab8b6d950149f332638c5707de74, ReleaseTagName: 20200719.1
2020-08-10T01:48:58.5882672Z 
2020-08-10T01:48:58.5886829Z Build Operation ID: |FrnAbkwBaJU=.dcbec6d1_
2020-08-10T01:48:58.5890863Z Repository Commit : 2d842cbb4d3a5b25b280ae91b68292b0bf143b3b
2020-08-10T01:48:58.5895213Z 
2020-08-10T01:48:58.6060633Z Detecting platforms...
2020-08-10T01:48:59.0408023Z Detected following platforms:
2020-08-10T01:48:59.0417270Z   nodejs: 12.18.2
2020-08-10T01:48:59.0422504Z   php: 7.3.15
2020-08-10T01:48:59.0460020Z Version '12.18.2' of platform 'nodejs' is not installed. Generating script to install it...
2020-08-10T01:48:59.0477393Z Version '7.3.15' of platform 'php' is not installed. Generating script to install it...
2020-08-10T01:48:59.2396428Z 
2020-08-10T01:48:59.2467606Z Using intermediate directory '/bin/staticsites/ss-oryx/app-int'.
2020-08-10T01:48:59.2475142Z 
2020-08-10T01:48:59.2480480Z Intermediate directory doesn't exist, creating it...'
2020-08-10T01:48:59.2486626Z 
2020-08-10T01:48:59.2490467Z Copying files to the intermediate directory...
2020-08-10T01:48:59.3231058Z Done in 0 sec(s).
2020-08-10T01:48:59.3235698Z 
2020-08-10T01:48:59.3240052Z Source directory     : /bin/staticsites/ss-oryx/app-int
2020-08-10T01:48:59.3243945Z Destination directory: /bin/staticsites/ss-oryx/app
2020-08-10T01:48:59.3249060Z 
2020-08-10T01:48:59.3249656Z 
2020-08-10T01:48:59.3249939Z Downloading and extracting nodejs version 12.18.2 to /tmp/oryx/platforms/nodejs/12.18.2...
2020-08-10T01:48:59.7849835Z Downloaded in 0 sec(s).
2020-08-10T01:48:59.7855568Z Verifying checksum...
2020-08-10T01:48:59.8758363Z Extracting contents...
2020-08-10T01:49:00.6022275Z Done in 1 sec(s).
2020-08-10T01:49:00.6036341Z 
2020-08-10T01:49:00.6046027Z 
2020-08-10T01:49:00.6050743Z Downloading and extracting php version 7.3.15 to /tmp/oryx/platforms/php/7.3.15...
2020-08-10T01:49:00.8085491Z Downloaded in 0 sec(s).
2020-08-10T01:49:00.8126591Z Verifying checksum...
2020-08-10T01:49:00.8671340Z Extracting contents...
2020-08-10T01:49:01.2830235Z Done in 1 sec(s).
2020-08-10T01:49:01.2833089Z 
2020-08-10T01:49:01.2837098Z 
2020-08-10T01:49:01.2840780Z Downloading and extracting php-composer version 1.9.3 to /tmp/oryx/platforms/php-composer/1.9.3...
2020-08-10T01:49:01.5787060Z Downloaded in 0 sec(s).
2020-08-10T01:49:01.5787355Z Verifying checksum...
2020-08-10T01:49:02.8493443Z 
2020-08-10T01:49:02.8493745Z 
2020-08-10T01:49:02.8493957Z ---End of Oryx build logs---
2020-08-10T01:49:02.8502015Z Oryx has failed to build the solution.
2020-08-10T01:49:02.8640887Z 
2020-08-10T01:49:02.8641337Z For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
2020-08-10T01:49:02.8641745Z If you believe this behavior is unexpected, please raise a Github issue at https://github.com/azure/static-web-apps/issues/
2020-08-10T01:49:02.8642219Z Exiting
```

**Comment by miwebst** [comment] 2020-08-10 15:41
@kichalla any ideas? looks like Oryx may be throwing when verifying the checksum?

**Comment by SeanKilleen** [comment] 2020-08-10 15:43
@miwebst that's what I was thinking at first as well.

If there's an additional setting that will provide more verbosity, please let me know and I'll include more detailed output.

**Comment by kichalla** [comment] 2020-08-10 17:25
@SeanKilleen Thanks for bringing this to our attention. Just curious, does you app actually use PHP? If you are not indeed using PHP, you can disable detection and building PHP related stuff using `DISABLE_PHP_BUILD=true` environment setting.

**Comment by SeanKilleen** [comment] 2020-08-10 18:25
@kichalla using that environment variable seems to have resolved the symptom -- thanks!

Is this a workaround to an issue, or something I should have done / known to do?

**Comment by kichalla** [comment] 2020-08-10 18:37
@SeanKilleen ideally you should not see this happening so what I suggested earlier was just a workaround for time . Would it be possible to share your repo so that we can try to repro the issue that you were seeing?

**Comment by SeanKilleen** [comment] 2020-08-10 18:48
@kichalla it is a private repo, but I will invite you and @miwebst as collaborators so that you can view it (it's just a brochure site for a product I'm kicking around.) . It's a pretty basic angular app which makes me think the issue will lie in either the github actions config or something going wrong with the SWA build container itself (perhaps something in oryx?)

**Comment by kichalla** [comment] 2020-08-10 19:05
@SeanKilleen Thanks for the repo details. I am taking a look at it now. Will keep you updated.

**Comment by kichalla** [comment] 2020-08-10 21:21
On looking deeper I found that the app that you are using does have some PHP based files and hence Oryx was trying to setup the environment with the pre-reqs which it assumes might be required for successfully building the app. (I was initially thinking if Oryx's detection of PHP was incorrect but that is fine)

Now regarding the error when downloading and verifying the PHP-Composer, I am not really sure why it happened at that time. Unfortunately I could not get much help from the logs that got generated for your build. However I tried it couple of times at my end that it go through fine. I am wondering if it was just a network issue at that time. 

So could you please revert back the earlier workaround (actually your app might need PHP so disabling it is not the right solution actually) and try again and see if it reproduces consistently?

**Comment by SeanKilleen** [comment] 2020-08-10 21:25
@kichalla interesting. These appear to be some files that I'd accidentally copied over from the theme. I definitely do not need PHP and the app is purely Angular (I'll be using functions or another service to handle sending mail, etc.)

I will revert the workaround and see if I can cause the issue again. 👍

**Comment by SeanKilleen** [comment] 2020-08-10 21:31
Removing the workaround indeed causes the build to fail again with the same issue -- an apparent failure at or after the "Verifying checksum" point of PHP composer.

I will remove the PHP files and see if this updates the auto-detection (I was indeed confused as to why it was attempting to add build steps for PHP). 

After that point, my issue is resolved but I'm happy to continue your access -- this commit reliably will produce the issue: https://github.com/SeanKilleen/skillustrator-frontend/commit/e217f91a5b62040fefdecbde850ab612d53c4dd8

You have my permission to branch from that commit and test fixes to the process in whatever way you deem appropriate.

**Comment by SeanKilleen** [comment] 2020-08-10 21:34
Removing the PHP files has resolved the symptom -- oryx no longer detects PHP and skips those steps.

**Comment by kichalla** [comment] 2020-08-20 11:46
@SeanKilleen Thanks for your patience. The php-composer issue should be fixed now.

**Comment by SeanKilleen** [comment] 2020-08-20 12:01
No worries at all! Is there any confirmation you'd like me to do on my end?

**Comment by kichalla** [comment] 2020-08-25 20:50
> Is there any confirmation you'd like me to do on my end? Those files didn't belong there to begin with, but I can place them back if you want to check the outcome.

No that is not required. Thanks for all the help!

**Closed** 2020-08-25 20:52 UTC
