### ISSUE TITLE
The content server has rejected the request with: BadRequest 147 Reason: The size of the function content was too large. The limit for this static site is 31457280 bytes

### ISSUE THREAD

**Issue by anirugu** [Azure/static-web-apps#247] opened 2020-12-25 10:26 UTC
My problem is much similar to this one https://github.com/Azure/static-web-apps/issues/214

I was making a POC app. I did use the Google.Cloud.Firebase I see my bin debug folder is 195MB. Is there any chance to use Firebase in c#. When this thing will be come under GA. 

I am looking for solution regarding this.

**Comment by anthonychu** [comment] 2020-12-29 07:09
This limit will be raised to 100MB soon. I think this is the compressed size, so it’s possible that you may be under the limits, depending on how well the artifacts compress. /cc @annaji-msft

**Comment by miwebst** [comment] 2021-02-03 19:40
We have updated this limit to 100 MB, you should be able to retry!

**Comment by anirugu** [comment] 2021-02-04 04:01
Thanks @miwebst  I will check and let you know

**Comment by nathanjford** [comment] 2021-03-10 05:43
I am having an issue deploying a super simple api based on this example: https://github.com/Azure-Samples/ms-identity-nodejs-webapi-azurefunctions . I think the problem is the node_modules folder gets big (like > 550Mb) even when specifying the '--production' flag. The 'Function' package.json has ~8 dependencies, so not a whole lot. Is there a way to get around this in gitHub actions? Thanks

**Comment by anthonychu** [comment] 2021-03-10 06:44
@nathanjford If you have Azure Functions Core Tools as a [dependency](https://github.com/Azure-Samples/ms-identity-nodejs-webapi-azurefunctions/blob/df367d35a48fb333fe387e25c630aaa612047e34/Function/package.json#L29), try removing it.

**Comment by nathanjford** [comment] 2021-03-14 10:19
Excellent, that reduced the size significantly! Thanks a lot.

**Comment by horihiro** [comment] 2021-05-02 00:36
Do we have a plan that the function content limit will be increased further? The deployment which includes `puppeteer` is failed as the following screenshot due to the size of `puppeteer`. Or do we have any workaround to deploy this?

![image](https://user-images.githubusercontent.com/4566555/116798350-70d5ca00-ab29-11eb-92eb-b1074b7bf4f4.png)

**Comment by miwebst** [comment] 2021-05-14 23:51
Closing this as well as BYOF is the recommended option right now for getting around this limit. See above issue for doc link.

**Closed by miwebst** 2021-05-14 23:51 UTC
