### ISSUE TITLE
APIs dont work on staging environment

### ISSUE THREAD

**Issue by Power-Maverick** [Azure/static-web-apps#1222] opened 2023-07-10 21:23 UTC
**Describe the bug**

Whenever we create a PR against a branch that triggers the deployment to the staging environment and if no changes are done in the `api` the build is successful but the APIs don't actually work.

My setup:
- React TypeScript app
- Managed API; but these managed APIs are calling some Azure resources for which we have configurations in the app settings

Any managed API that needs to call the Azure resource does not work

**Expected behavior**
Staging environment should work similar to how the main environment works.

**Additional context**
Any managed API that are self-sufficent works fine in the staging environment. In my case, that is only 1% of the case so the majority of the time I cannot test on the staging environment; making it useless.

**Comment by thomasgauvin** [comment] 2023-07-17 19:52
@Power-Maverick can you try republishing your preview environment to see if that fixes it? Trying to scope it down to the root cause

**Comment by Power-Maverick** [comment] 2023-07-17 20:25
It's been happening for a long time for a few months now. I have re-tried this many times and this is my observation.
- When changes are done in /api & /app it works
- When changes are done in /api it works
- When changes are done in /app it DOES NOT WORK

If I do any change (even a simple space) under /api for the last option it starts working. But not always /api will have a chnage.

**Comment by thomasgauvin** [comment] 2023-07-18 14:53
@Power-Maverick , I can confirm that the APIs do get deployed as can be seen here https://calm-plant-06513c503-3.westeurope.2.azurestaticapps.net/ https://github.com/thomasgauvin/swa-vanilla-api-2/actions/runs/5588883103, but that they don't inherit the app settings which is likely what is causing your issue with calling downstream services

**Comment by Power-Maverick** [comment] 2023-07-20 21:37
The configuration does exist. I checked that first. As I said if any API changes are made they do work from get-go. And any new PR the configurations are copied over.
![image](https://github.com/Azure/static-web-apps/assets/36135520/00a99b4a-0081-4ff7-8485-34a594a0e705)

**Comment by thomasgauvin** [comment] 2023-07-24 14:59
@Power-Maverick, yes, I'm confirming that this issue exists, you will see them in the Portal but they do not propagate to the Azure Functions being used behind the scenes. Fix is being worked on

Same issue on the topic: https://github.com/Azure/static-web-apps/issues/1178

**Comment by thomasgauvin** [comment] 2023-08-01 14:05
Update, this issue has been fixed, app settings are now propagated to the managed Azure Function correctly for preview environments! Closing this issue

**Closed by thomasgauvin** 2023-08-01 14:05 UTC
