### ISSUE TITLE
Unable to switch hosting plans

### ISSUE THREAD

**Issue by irwinwilliams** [Azure/static-web-apps#454] opened 2021-06-02 03:20 UTC
I want to switch from Free to Standard hosting plans.
When I try to do so, I get this error:
![image](https://user-images.githubusercontent.com/1428703/120419126-d1764380-c32f-11eb-8c25-153b4191bd94.png)

I had initially chosen to configure my SWA to use Azure DevOps. Looks like I'll have to create a new app and point to a repo in GitHub instead.

**Comment by miwebst** [comment] 2021-06-02 03:30
Hey @irwinwilliams, this is something that is fixed in our upcoming release. I believe this is a duplicate of https://github.com/Azure/static-web-apps/issues/427, do you mind if we close this and use the other issue for tracking?

There is also a workaround we've posted there that you can try out.

**Closed** 2021-06-02 03:35 UTC
