### ISSUE TITLE
Failure during distribution

### ISSUE THREAD

**Issue by Robotuner** [Azure/static-web-apps#596] opened 2021-10-03 13:40 UTC
Bug occurs on Azure Static Web Apps CI/CD site.
https://github.com/Robotuner/PhotoViewer/actions?query=workflow%3A"Azure%20Static%20Web%20Apps%20CI%2FCD"%20branch%3Amaster

This morning, I had one successful built then started getting errors on subsequent builds.  Looking at the Build and deploy log, I see two errors.  The first is
Error: Could not detect language from repo.
I believe I have seen this before but those builds deployed anyway.  What I note is new occurs next:

Finished building app with Oryx
Either no Api directory was specified, or the specified directory was not found. Azure Functions will not be created.
Zipping App Artifacts
Done Zipping App Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.722505(s)
Status: InProgress. Time: 15.9998059(s)
Status: InProgress. Time: 31.4831591(s)
Status: InProgress. Time: 46.7378103(s)
Status: InProgress. Time: 61.9771657(s)
Status: InProgress. Time: 77.0871815(s)
Status: InProgress. Time: 92.4185068(s)
Status: InProgress. Time: 107.5035288(s)
Status: InProgress. Time: 122.7169736(s)
Status: InProgress. Time: 137.9228606(s)
Status: InProgress. Time: 153.1478009(s)
Status: InProgress. Time: 168.2483484(s)
Status: InProgress. Time: 183.523484(s)
Status: Failed. Time: 198.6058985(s)
Deployment Failed :(
Deployment Failure Reason: Failure during content distribution.

I reverted my code back to the previous successful deployment and still get the failure.  Is this a problem on your end or my code?

**Comment by gat786** [comment] 2021-10-04 05:14
The repository you have linked is a private repository. So it gives 404 on visit.

**Comment by Chw-Lho** [comment] 2021-10-04 09:12
I am also running into this issue, with a pipeline that worked 3 days ago and hasn't been changed since.
It could seem like something is broken?

**Comment by artigat1** [comment] 2021-10-04 10:16
I'm seeing this behaviour today with a repo that has worked fine for a couple of months.

**Comment by arnoldboersma** [comment] 2021-10-04 11:42
I'm also running into the same issue, while this worked this weekend.

**Comment by arnoldboersma** [comment] 2021-10-04 12:32
Duplicate of #586

**Comment by miwebst** [comment] 2021-10-04 15:24
Yes this is an Azure issue, we are working with the responsible team to fix things as soon as possible. Sorry for the inconvenience, I'll post updates here as I have them.

**Comment by miwebst** [comment] 2021-10-04 15:25
Also closing the other issue as they are distinct issues with the same error message. We can use this one (active one) for tracking.

**Comment by miwebst** [comment] 2021-10-04 18:49
The responsible team has rolled out an initial mitigation. We are seeing positive numbers on our side, can anyone affected retry and see if they are still affected?

**Comment by Robotuner** [comment] 2021-10-04 18:55
It succeed building and deploying the last failed job for me.

Thank you.

**Comment by Chw-Lho** [comment] 2021-10-04 19:01
It's working for me as well, thanks!

**Comment by arnoldboersma** [comment] 2021-10-04 19:01
The same here! thanks for the quick action!
![image](https://user-images.githubusercontent.com/7750558/135908960-a973995c-5778-4204-ba14-710151b34f39.png)

**Closed** 2021-10-09 23:21 UTC
