### ISSUE TITLE
Any known issues for build pipeline with Oryx and Hugo?

### ISSUE THREAD

**Issue by jobullen** [Azure/static-web-apps#412] opened 2021-05-13 15:51 UTC
Been trying to do a publish for the last few days and it just stops and times out on the building site point. Used to work fine and site builds locally, could not find any other logs. Made a custom action to enable verbose after looking at your internal source and it did not provide much more information. Here is one of the errors, the job is still failing and timing out after 15mins.

Successfully tagged 8a33c1:bbe0bdaef33f595a0a359b84d4173c9b 
95/usr/bin/docker run --name a33c1bbe0bdaef33f595a0a359b84d4173c9b_126bab --label 8a33c1 --workdir /github/workspace --rm -e INPUT_AZURE_STATIC_WEB_APPS_API_TOKEN -e INPUT_REPO_TOKEN -e INPUT_ACTION -e INPUT_APP_LOCATION -e INPUT_API_LOCATION -e INPUT_APP_ARTIFACT_LOCATION -e INPUT_API_BUILD_COMMAND -e INPUT_OUTPUT_LOCATION -e INPUT_APP_BUILD_COMMAND -e INPUT_ROUTES_LOCATION -e INPUT_SKIP_APP_BUILD -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true ... 
97DeploymentId: 12df2e02-3d79-458c-a19f-a3c97a85ade2 
98 
99Verbose logging enabled 
100Build timeout not specified, defaulting to 15 minutes 
101App Directory Location: '/hugo-blog' was found. 
102Api Directory Location: 'api' was found. 
103Starting to build app with Oryx 
104Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx 
105Calling oryx build /github/workspace/hugo-blog -o /bin/staticsites/ss-oryx/app --manifest-dir /bin/staticsites/ss-oryx/app-manifest -p prune_dev_dependencies -p require_build -p disable_recursive_lookup=true -p ORYX_APP_TYPE="static-sites" 
106---Oryx build logs--- 
107 
108 
109Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx 
110You can report issues at https://github.com/Microsoft/Oryx/issues 
111 
112Oryx Version: 0.2.20210410.1, Commit: e73613ae1fd73c809c00f357f8df91eb984e1158, ReleaseTagName: 20210410.1 
113 
114Build Operation ID: |kObMwcaURbk=.1e049c56_ 
115Repository Commit : 90481206f7763dcfa2b53557ceddf0d1b1a9d77d 
116 
117Detecting platforms... 
118Detected following platforms: 
119 hugo: 0.81.0 
120 
121 
122Source directory : /github/workspace/hugo-blog 
123Destination directory: /bin/staticsites/ss-oryx/app 
124 
125 
126Using Hugo version: 
127hugo v0.81.0-59D15C97+extended linux/amd64 BuildDate=2021-02-19T17:07:12Z VendorInfo=gohugoio 
128 
129Start building sites …

**Comment by anthonychu** [comment] 2021-05-13 22:14
@jobullen Is your repo public? Would like to try the build ourselves.

This looks like something @burkeholland ran into in a Node build.

**Comment by jobullen** [comment] 2021-05-13 22:56
It is not but I can give you permissions. Who needs to be added?

**Comment by sytone** [comment] 2021-06-12 01:43
@anthonychu were you able to see the issue? It is still not publishing yet building fine locally.

**Comment by anthonychu** [comment] 2021-06-12 15:46
Sorry that got lost in my GitHub notifications. Do you mind re-inviting me?

**Comment by sytone** [comment] 2021-06-12 16:08
Invite sent.

**Comment by anthonychu** [comment] 2021-06-13 00:49
Thanks @sytone. I'm able to reproduce this in the Static Web Apps GitHub workflow.

However, I'm also seeing this when building the app locally by running `hugo` in the `hugo-blog` folder on macOS as well as on Linux in a Codespace. It just hangs forever. If you haven't already, can you try this yourself in a *nix environment?

**Comment by sytone** [comment] 2021-06-13 04:44
Just cloned to a new folder and installed hugo in WSL. No build issues. Also hugo server works fine serving the files. 

sytone@HOMEDESKTOP:~/personal-blog/hugo-blog$ hugo
Start building sites …

                   | EN
-------------------+------
  Pages            | 279
  Paginator pages  |  34
  Non-page files   |  19
  Static files     |   0
  Processed images |   0
  Aliases          |  71
  Sitemaps         |   1
  Cleaned          |   0

Total in 496 ms
sytone@HOMEDESKTOP:~/personal-blog/hugo-blog$ hugo version
hugo v0.83.1+extended linux/amd64 BuildDate=unknown

**Comment by anthonychu** [comment] 2021-06-13 22:36
I can confirm I'm using v0.83.1 as well.

I've also tried it in a docker container with the same result:

```bash
cd hugo-blog
docker run --rm -it -v $(pwd):/src klakegg/hugo:0.83.1 --verbose
```

Possibly related to this issue: https://github.com/gohugoio/hugo/issues/8166

**Comment by sytone** [comment] 2021-06-14 20:58
I removed the txt file and json files in content and the site build worked. Will look at how to add routes to site another way.

**Comment by sytone** [comment] 2021-06-14 21:03
I placed them in static and published and it is now working fine. Thanks. We can close this up.

**Comment by anthonychu** [comment] 2021-06-20 00:53
Thanks @sytone. This is a weird one. I'll close for now.

**Closed by anthonychu** 2021-06-20 00:53 UTC
