### ISSUE TITLE
Upload Timed Out. Unsure if deployment was successful or not.

### ISSUE THREAD

**Issue by tejaswankalluri** [Azure/static-web-apps#1396] opened 2024-01-21 06:55 UTC
![image](https://github.com/Azure/static-web-apps/assets/49343044/5c3de4f6-cdc6-42d9-9b67-636593122830)

**Comment by FinOCE** [comment] 2024-01-21 07:00
I'm experiencing the same issue, first occurred for me half an hour ago. I've attempted to deploy two separate SWA sites and both experiencing the issue. It looks to me like the deployments did not work as I don't see my changes reflected on the site. We'll probably just have to wait until its fixed before we can deploy anything again.

**Comment by pondchamp** [comment] 2024-01-21 07:30
+1, this issue is blocking all SWA deployment pipelines on our end

**Comment by nerblock** [comment] 2024-01-21 07:40
Same on our end, also the failed deployment broke the staging site.

**Comment by sonuame** [comment] 2024-01-21 08:42
Same here for me

**Comment by takawww** [comment] 2024-01-21 08:53
same here

**Comment by 58836980** [comment] 2024-01-21 08:57
working now~

**Comment by youngox9** [comment] 2024-01-21 09:09
same here

**Comment by tejaswankalluri** [comment] 2024-01-21 09:10
> working now~

Yes It's working now

**Comment by takawww** [comment] 2024-01-21 09:11
> working now~

Yes, is it working now, thanks for notice

**Comment by sonuame** [comment] 2024-01-21 11:36
Yes its working again for me as well

**Comment by K3llr** [comment] 2024-01-23 17:20
Same issue. Not working currently.

**Comment by joshuaolusayo** [comment] 2024-01-28 12:06
I am also having the issue... The problem is that.. how will I know if the deployment is successful because the build seems to be failing with the error above.

The first time I checked my latest build, it was not successful. No changes on the server also. I re-run the job in the github actions and it was not successful again - the build failed. When I checked the website, the changes seems to have been uploaded... How do I know next time that my update has been successfully deployed if the changes made cannot really be easily seen on the website?

**Comment by owljackob** [comment] 2024-01-28 13:55
+1, started recently.

**Comment by kristiangronli** [comment] 2024-01-28 13:57
same issue here

**Comment by chenn88** [comment] 2024-01-28 18:19
Having this issue also.

**Comment by bcampru** [comment] 2024-01-28 20:25
We are also having this issue

**Comment by chenn88** [comment] 2024-01-28 20:32
It seems that mine does build and deploy (eventually) on SWA, despite the timeout from GH workflow. When I checked environments on SWA it said uploading for a while then changed to ready, but the GH workflow still had it recorded as incomplete.

**Comment by phoenixz0024** [comment] 2024-01-28 21:29
same for us

**Comment by tuomasorhanen** [comment] 2024-01-29 08:14
Same issue here!

**Comment by boriseetgerink** [comment] 2024-01-29 08:56
I'm also affected by this issue. Deployments worked fine without functions, but started to timeout when I added functions to my site.

**Comment by compinschools** [comment] 2024-01-29 10:11
Getting the same issue here

**Comment by rduque1** [comment] 2024-01-29 10:25
Same issue here and when I build the app and check the size it 's only 51MB

**Comment by firasnajjar** [comment] 2024-01-29 10:31
same here

**Comment by egbertbeuker** [comment] 2024-01-29 10:41
Same, Azure Static App deployment

**Comment by tsubakimoto** [comment] 2024-01-29 10:42
same issue here

**Comment by chenn88** [comment] 2024-01-29 10:44
> It seems that mine does build and deploy (eventually) on SWA, despite the timeout from GH workflow. When I checked environments on SWA it said uploading for a while then changed to ready, but the GH workflow still had it recorded as incomplete. 

This is no longer working for me at all. Now just taking about 30minuted to say failed in the SWA environment.

**Comment by JorisDePoris** [comment] 2024-01-29 11:50
Same issue here

**Comment by jpaholik** [comment] 2024-01-29 11:55
Since today I have the same issue

**Comment by grantvine-sc** [comment] 2024-01-29 12:07
Also have this issue, any updates ?

**Comment by krisnashaypp** [comment] 2024-01-29 12:23
+1

**Comment by GojkoGalonja** [comment] 2024-01-29 12:28
Same issue

**Comment by Freshchris01** [comment] 2024-01-29 12:45
Same issue here. Did you open a support ticket to raise awareness?

**Comment by jesseflikweerteo** [comment] 2024-01-29 13:05
@egbertbeuker, it's likely not a GitHub issue as it's present on Azure DevOps as well.

**Comment by egbertbeuker** [comment] 2024-01-29 13:26
@jesseflikweerteo thank's, do you know if this issue has been reported to Microsoft and where I can find its status?

**Comment by jesseflikweerteo** [comment] 2024-01-29 13:29
@egbertbeuker, no, I don't.

**Comment by blackspike** [comment] 2024-01-29 13:40
same

**Comment by Freshchris01** [comment] 2024-01-29 13:45
I tried to deploy my React frontend manually with the [swa cli](https://azure.github.io/static-web-apps-cli/docs/cli/swa-deploy) and experience the issue without Github Actions as well.

From my experience opening support tickets and including a link to the issue will help raise awareness.

**Comment by kornhammer** [comment] 2024-01-29 14:08
+ same issue here as well

**Comment by christie-hill-za** [comment] 2024-01-29 14:18
I have also been experiencing this issue for the past two hours trying to deploy a Nuxt Static Web App to Azure. No build errors, just times out after about 6-9 minutes 

![image](https://github.com/Azure/static-web-apps/assets/83393649/8d9715db-7088-44c0-9463-c53376bb3c41)

**Comment by ulfdev** [comment] 2024-01-29 14:25
Same here, just started to happen today.

**Comment by rjoshi** [comment] 2024-01-29 14:26
Facing same issue since yesterday evening, on Azure protal I noticed the deployment eventually happens but the github action is not passing.


---End of Oryx build logs---
Try to validate location at: '/bin/staticsites/591fd2a1-1e5f-4550-89ac-fbe2fcac995c-swa-oryx/app/.next'.
Oryx has determined that the app build artifacts are in the '.next' directory. If this is incorrect please specify the app artifact location.
Finished building app with Oryx
Detected standalone folder, so using it for deployment.
Repackaged Next.js app to deploy on the backend.
Skipping step to build /bin/staticsites/591fd2a1-1e5f-4550-89ac-fbe2fcac995c-swa-oryx/app/.next/standalone with Oryx
Function Runtime Information. OS: linux, Functions Runtime: ~4, node version: 18
Zipping Api Artifacts
Done Zipping Api Artifacts
Zipping App Artifacts
Done Zipping App Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.0888352(s)
Status: InProgress. Time: 15.169784(s)
Status: InProgress. Time: 30.2546991(s)
Status: InProgress. Time: 45.341156(s)
Status: InProgress. Time: 60.4209056(s)
Status: InProgress. Time: 75.5075716(s)
Status: InProgress. Time: 90.5889109(s)
Status: InProgress. Time: 105.665616(s)
Status: InProgress. Time: 120.7504045(s)
Status: InProgress. Time: 135.8308853(s)
Status: InProgress. Time: 150.9156537(s)
Status: InProgress. Time: 166.007786(s)
Status: InProgress. Time: 181.0956602(s)
Status: InProgress. Time: 196.1774999(s)
Status: InProgress. Time: 211.2725957(s)
Status: InProgress. Time: [226](https://github.com/StarSpark-AI/worksheets/actions/runs/7692546319/job/20974294487#step:4:227).351[232](https://github.com/StarSpark-AI/worksheets/actions/runs/7692546319/job/20974294487#step:4:233)3(s)
Upload Timed Out. Unsure if deployment was successful or not.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting

**Comment by danbord** [comment] 2024-01-29 15:19
same here

**Comment by eolasd** [comment] 2024-01-29 15:42
same here, build runs ok, stuck uploading on swa..
![failswa](https://github.com/Azure/static-web-apps/assets/15805713/2847036a-649a-409f-8c45-497c4641aaac)

Github actions log shows build completing but timeout on polling the deploy to azure.

**Comment by mikeschepers4** [comment] 2024-01-29 15:56
Same here

**Comment by bjoernAIO** [comment] 2024-01-29 16:23
same for us

**Comment by owljackob** [comment] 2024-01-29 17:39
https://github.com/Azure/static-web-apps/issues/1404#issuecomment-1915188240

**Comment by danielmellqvist** [comment] 2024-01-29 20:51
Same issue here!

**Comment by aerickson-clt** [comment] 2024-01-29 21:20
Same issue here

**Comment by 20-dishes** [comment] 2024-01-29 22:14
Same issue, started earlier today

**Comment by JoelMTaylor** [comment] 2024-01-29 23:31
Now, I cannot get it to succeed at all. Anyone else having it time out _always_?

**Comment by hugoforte** [comment] 2024-01-29 23:34
Mine are always timing out as well

**Comment by chenn88** [comment] 2024-01-29 23:34
> Now, I cannot get it to succeed at all. Anyone else having it time out _always_? 

Yeah tried several times today but timing out on every attempt. Looks like the Azure are aware and looking into it.

**Comment by asiz15** [comment] 2024-01-29 23:50
:eyes:

**Comment by eolasd** [comment] 2024-01-30 00:18
Commenting out API_LOCATION fixed issue for me (see #1404)
Deploy successful just now.

**Comment by aerickson-clt** [comment] 2024-01-30 00:42
> Commenting out API_LOCATION fixed issue for me (see #1404) Deploy successful just now.

I can confirm this, but since my app has a managed API it is not a viable workaround.  I guess an alternative would be to use an unmanaged Azure Function, but I this is not practical considering that the issue will soon be fixed.

**Comment by javiercoh** [comment] 2024-01-30 02:24
> Commenting out API_LOCATION fixed issue for me (see #1404) Deploy successful just now.

this also worked for me

**Comment by aerickson-clt** [comment] 2024-01-30 04:24
According to the tracking at https://app.azure.com/h/2S4Z-JTG/6d979c the issue has been resolved, and my deployment (with api_location) is now working.

**Comment by GojkoGalonja** [comment] 2024-01-30 07:26
I just ran my pipeline and it is deployed with no issues.

**Comment by joshuaolusayo** [comment] 2024-01-30 07:54
It's working fine now from my end also...

**Comment by thomasgauvin** [comment] 2024-03-04 14:12
This issue was resolved in January, closing. Please open a new issue if you encounter this in the future.

**Closed by thomasgauvin** 2024-03-04 14:12 UTC

**Comment by sarveshrekhta** [comment] 2024-08-31 15:36
I m getting same issue. Please suggest. Its critical.

**Comment by farazirfan47** [comment] 2024-09-20 08:54
same issue

**Comment by carlohoanguyen** [comment] 2025-08-27 07:12
Same issue here. Did anyone find a solution or the root problem?

**Comment by rduque1** [comment] 2025-08-27 08:58
For me it was the middleware, the Azure health checks need to work in order to deploy successfully the application:
[https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid#configure-routing-and-middleware-for-deployment](https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid#configure-routing-and-middleware-for-deployment)

Maybe this helps

**Comment by carlohoanguyen** [comment] 2025-08-28 10:52
Trying to deploy a minimal NextJS app to SWA with Identity token or Azure access token still times out.

Followed the docs on configuration: https://learn.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=aat&pivots=github-actions

Next.js version: 15.4.6
