### ISSUE TITLE
`x-ms-client-principal` header not included when request rewritten to API via `navigationFallback`

### ISSUE THREAD

**Issue by geoffrich** [Azure/static-web-apps#1053] opened 2023-01-24 04:16 UTC
**Describe the bug**

The `x-ms-client-principal` header is not consistently sent to the Static Web App's API function. In particular, when the request is rewritten to the API route via `navigationFallback` and the route does not have an `allowedRoles`, the header is not present.

If the route does have an `allowedRoles` or if the route is rewritten to the API route outside of `navigationFallback`, then the header is present.

**To Reproduce**

[live demo](https://green-desert-07828041e.2.azurestaticapps.net/)

[demo repo](https://github.com/geoffrich/swa-client-principal-repro)

Given a Static Web App with an Azure Function API available at `/api/auth-test`, an index.html file, and the following config:

```json
{
  "routes": [
    {
      "route": "/api-rewrite",
      "rewrite": "/api/auth-test"
    },
    {
      "route": "/protected",
      "allowedRoles": ["authenticated"]
    }
  ],
  "navigationFallback": {
    "rewrite": "/api/auth-test"
  }
}
```

1. Login (e.g. via /.auth/login/github)
2. Navigating to `/api/auth-test` (the API function), `/api-rewrite` (which rewrites the request via `routes`), and `/protected` (which rewrites the request via `navigationFallback` and has an `allowedRoles`) all correctly rewrite the request to the API function at `/api/auth-test` and include the x-ms-client-principal header
3. Navigating to `/whatever` (which rewrites the request to the API function via `navigationFallback` and does not have an `allowedRoles`) _does not include_ the x-ms-client-principal header

You can clearly see this on my demo site linked above. The API function returns the `x-ms-client-principal` headers it receives.

**Expected behavior**
The `x-ms-client-principal` header is provided for all requests to the API.

**Screenshots**
n/a

**Device info (if applicable):**
n/a

**Additional context**
I maintain the [SvelteKit](https://kit.svelte.dev/) integration for Azure Static Web Apps, [svelte-adapter-azure-swa](https://github.com/geoffrich/svelte-adapter-azure-swa). This issue is preventing SvelteKit users from getting consistent access to authentication info via the `x-ms-client-principal` header.

The adapter works by rewriting requests in `navigationFallback` to an Azure function that runs the SvelteKit request handler to server-side render the page, among other things. If the requested route is not present in the SWA route config with an `allowedRoles` specified, then the request does not have access to authentication info via the header.

**Comment by thomasgauvin** [comment] 2023-01-24 13:46
Hey @geoffrich! Thanks for the feedback and the work on svelte-adapter-azure-swa. We'll look into this

**Comment by geoffrich** [comment] 2023-01-24 17:18
Thanks! It's worth noting that the issue I report here only happens on the deployed site - when running the demo locally with the SWA CLI, I get the header back in all cases.

**Comment by derkoe** [comment] 2023-02-13 08:39
Just ran into the same issue - here is a demo repository to reproduce this: https://github.com/derkoe/azure-swa-auth-issue-with-nav-fallback (here is the deployed version https://proud-moss-0ed9eb403-test.westeurope.1.azurestaticapps.net/)

**Comment by derkoe** [comment] 2023-02-28 07:23
There is a workaround for this:
* adding an "allowedRoles" with route "*" 
* adding all non-secured routes (a long list) in front of it

Here is an example for this:
```json
{
  "navigationFallback": {
    "rewrite": "/api/render"
  },
  "routes": [
    {
      "route": "/manifest.json"
    },
    {
      "route": "/service-worker.js"
    },
    {
      "route": "/robots.txt"
    },
    {
      "route": "/static/*"
    },
    ...
    {
      "route": "*",
      "allowedRoles": ["authenticated"]
    }
  ]
}
```

**Comment by thomasgauvin** [comment] 2023-07-20 21:15
Hi @derkoe and @geoffrich, this has now been fixed and you can access the x-ms-client-principal in requests rewritten to an api path. I've forked and edited your repo derkoe, and here it is working: https://github.com/thomasgauvin/azure-swa-auth-issue-with-nav-fallback Try it out! [https://yellow-ocean-03d2d7403.3.azurestaticapps.net/thisisa404](https://yellow-ocean-03d2d7403.3.azurestaticapps.net/thisisa404)

**Comment by derkoe** [comment] 2023-07-27 20:06
Thx @thomasgauvin - it seems to work now without the workaround.

**Comment by thomasgauvin** [comment] 2023-07-27 20:26
Excellent, thanks for the confirmation @derkoe, closing this issue

**Closed by thomasgauvin** 2023-07-27 20:26 UTC

**Comment by MykalMachon** [comment] 2023-12-07 18:17
Hi all, 
We're still experiencing this issue. I've yet to try @derkoe 's workaround but it looks like around 30-40% of our requests are going to the API without that header which makes our app unusable in production. 

I can't share our application code with this thread as it's internal, but this only happens in one of our 2 environments. 
Our test resource group has no issues while our production one has had issues since it was deployed.

**Comment by ajames88** [comment] 2024-03-29 12:31
I am also experiencing the same issue as @MykalMachon in a Azure SWA which is receiving 401 Unauthorized responses from a connected Azure Container App which host our APIs.

Is there an easy to prevent this intermittent issue?

Issue also raised at: https://learn.microsoft.com/en-us/answers/questions/1635634/x-ms-client-principal-header-not-included-in-reque
