### ISSUE TITLE
Bug Report - Incorrect message when mapping a custom domain

### ISSUE THREAD

**Issue by cmaneu** [Azure/static-web-apps#161] opened 2020-09-28 19:37 UTC
**Steps to reproduce**
1. Create a first SWA, and map it to a custom domain
1. Create a second SWA, and map it to the exact same custom domain

**Expected result**
Either: 
- The domain is correctly mapped
- A clear error message says it's impossible because it's already mapped

**Actual result**
![image](https://user-images.githubusercontent.com/790974/94477669-7ef9eb80-01d2-11eb-90db-a562fc366712.png)

**Technical details**
The message returned by the API is correct, but not the displayed message
![image](https://user-images.githubusercontent.com/790974/94477904-cb452b80-01d2-11eb-87fb-4710986b6133.png)

**Comment by miwebst** [comment] 2020-09-29 21:44
We have added a work item for this and will get it fixed!

**Comment by aditechsachinc** [comment] 2020-11-08 09:40
Hi, I have a similar issue, tried to validate a subdomain, the validation process did not finish and after I try again I get the above error message. Is there a workaround to make this work quickly, before there is a proper fix?

**Comment by miwebst** [comment] 2020-11-10 17:22
Take a look at this issue, if your domain has CAA records then it may be causing us to fail to provision it. We are still working on blocking these up front https://github.com/Azure/static-web-apps/issues/163

**Comment by aditechsachinc** [comment] 2020-11-11 05:51
> Take a look at this issue, if your domain has CAA records then it may be causing us to fail to provision it. We are still working on blocking these up front #163

There are no CAA records. When I browse to the domain URL, I get "NET::ERR_CERT_COMMON_NAME_INVALID" and the certificate attached is as below:
![image](https://user-images.githubusercontent.com/38943043/98773958-ff398080-240f-11eb-8f8d-bef1ec85c2fc.png)

**Comment by miwebst** [comment] 2020-11-11 16:41
Gotcha, do you mind providing the hostname you are trying to add so we can take a look?

**Comment by aditechsachinc** [comment] 2020-11-11 16:44
> Gotcha, do you mind providing the hostname you are trying to add so we can take a look?

admin.bleap.app

**Comment by miwebst** [comment] 2020-11-12 01:07
@aditechsachinc we have looked into this and this is being caused by a bug on our side. We will work on getting a fix out for this asap. Thanks for your patience!

**Comment by aditechsachinc** [comment] 2020-11-18 07:33
> @aditechsachinc we have looked into this and this is being caused by a bug on our side. We will work on getting a fix out for this asap. Thanks for your patience!

@miwebst ,
Is there an expected timeframe for the fix? 
Also, is there a workaround? Will deleting and creating the staticwebapp resolve the issue?

**Comment by miwebst** [comment] 2020-11-18 18:13
Yes sorry for the delay, we have fixed the issue. If you delete and recreate the static web app it should resolve the issue!

**Comment by aditechsachinc** [comment] 2020-11-19 00:41
> Yes sorry for the delay, we have fixed the issue. If you delete and recreate the static web app it should resolve the issue!

Thanks, the domain was added successfully.

**Comment by justindmyers** [comment] 2021-01-08 21:49
Since this ticket is still open, I'm running into the same issue now. We just bought a brand new domain, set up the static website on 1/7/2021 and added the custom domain (`www.3dgolf.app`) but I'm getting the wrong url for the certificate just like the user above (`*.staticsites-prod-westus2.p.azurewebsites.net`).

**Comment by justindmyers** [comment] 2021-01-11 19:07
Just an update: it finally started working today. I'm not sure why it took 4 days, but at least it did start working at some point.

**Comment by Reshmi-Sriram** [comment] 2022-11-30 14:38
Closing due to no traction. Feel free to reopen if required!

**Closed by Reshmi-Sriram** 2022-11-30 14:38 UTC
Labels: bug, domains/certs

**Comment by cmaneu** [comment] 2022-12-02 20:27
Hi @Reshmi-Sriram, 
Did you tried if the issue is still there/if you're able to repro the issue?
