### ISSUE TITLE
Videos do not load on iPhones if Enterprise Grade Edge is switched on

### ISSUE THREAD

**Issue by danbasszeti** [Azure/static-web-apps#807] opened 2022-05-18 10:18 UTC
**Describe the bug**

When I have enterprise edge switched on and I push an app that has a .mp4 file  in it (referenced in HTML using the standard <video> tags) it will not load on an iPhone. When I push the same app to a static web app without enterprise edge switched on, the video will load absolutely fine. 

**To Reproduce**
1. Go to a deployed app with working videos e.g. https://zeti.co.uk 
2. Switch on Enterprise Edge and wait 30 minutes
3. Visit from an iPhone
4. Video will not load
5. Switch off Enterprise Edge
6. Visit from an iPhone
7. Video will work again

Sorry I can't provide the repo it is private. But the site the bug was observed on is https://zeti.co.uk (I have switched off enterprise edge now as its my live site). I have purposely reintroduced the bug on https://staging.zeti.co.uk so that you can see it

**Expected behavior**
I expected videos to continue to load and operate normally and benefit from the CDN speedup. 

**Device info (if applicable):**
 - OS: iOS
 - Browser: Chrome and Safari 
 - Version: latest

**Additional context**
I have strong suspicion that this is some kind of encoding/mimetype problem. I have the mimetypes correctly mapped in the staticwebapp.json, but I wonder if that isn't being reflected in CDN or something?

**Comment by danbasszeti** [comment] 2022-05-19 07:05
I've reintroduced the bug on https://staging.zeti.co.uk

**Comment by joslinmicrosoft** [comment] 2022-05-19 22:41
Hi @danbasszeti, thank you for reporting this and for the live repro. We are investigating and will post here with any updates.

**Comment by danbasszeti** [comment] 2022-05-20 09:04
Thanks @joslinmicrosoft, let me know if there's anything else I can do

**Comment by danbasszeti** [comment] 2022-06-21 18:38
Hi,

This bug is still apparent on my staging site - is there a prioritisation level to this? 

Cheers,
Dan

**Comment by joslinmicrosoft** [comment] 2022-06-23 15:20
Hi, sorry for the delay here. Unfortunately, we're still working on a solution; I will try to push to prioritize this fix. To your original point, I don't think it's anything to do with your mimetypes or configurations, so no need to try changing those.

**Comment by joslinmicrosoft** [comment] 2022-07-22 22:03
Hi @danbasszeti, we've just finished rolling out a fix for this. I can't view your repro site, as it's password protected, but please let us know if the issue is resolved or if you are still seeing unexpected behavior. Thanks!

**Comment by thomasgauvin** [comment] 2022-08-15 14:17
@joslinmicrosoft @danbasszeti Can we close this issue as fixed?

**Comment by danbasszeti** [comment] 2022-08-15 14:31
Hi apologies - thanks for this, it works perfectly. Great stuff!

**Closed** 2022-08-16 09:49 UTC
