### ISSUE TITLE
AAD Login Loop

### ISSUE THREAD

**Issue by akzaidi** [Azure/static-web-apps#219] opened 2020-11-23 19:49 UTC
Thanks for the wonderful service!

I am serving a static website with AAD authentication. Here is the `routes.json`:

```json
{
  "routes": [
    {
      "route": "/login",
      "serve": "/.auth/login/aad"
    },
    {
      "route": "/login/github",
      "serve": "/.auth/login/github"
    },
    {
      "route": "/.auth/login/twitter",
      "statusCode": "401"
    },
    {
      "route": "/.auth/login/facebook",
      "statusCode": "401"
    },
    {
      "route": "/.auth/login/google",
      "statusCode": "401"
    },
    {
      "route": "/*",
      "allowedRoles": ["authenticated"]
    }
  ],
    "platformErrorOverrides": [
        {
            "errorType": "Unauthenticated",
            "statusCode": 302,
            "serve": "/login"
        }
    ]
}
```

Basically, I only want AAD or github authentication, and want to serve `/login` if the user is not yet authenticated, otherwise serve the page they clicked on.

However, what we're finding is when a user tries to click on a link, they sometimes end up in an infinite AAD login-loop. Here are the console logs of one such example:

```
Console logs:
Navigated to https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code+id_token&redirect_uri=https%3A%2F%2Fidentity.azurestaticapps.net%2F.auth%2Flogin%2Faad%2Fcallback&client_id=d414ee2d-73e5-4e5b-bb16-03ef55fea597&scope=openid+profile+email&response_mode=form_post&nonce=e73ac765cd604d7db6b9aa6d011d1d6d_20201123181225&state=redir%3D%252F.auth%252Flogin%252Fdone
Navigated to https://login.microsoftonline.com/common/reprocess?ctx=rQIIAaWQv2sUQRzFb2_v1iQYDGJho1wRm8je_NiZ3eyGKxIwcKjcFQYslDCz37ns6O7OsjsBkzaNoEJqSxshdiGFpLJOFbCzshSxEEUQK9f8Czbv86r3gbfi0iFOloERphQFPwoU95ni0peShD4O1IzzmRI8juqrC0uPX0z1uwM6fvXz5Z_bax9vHjmjzNqqSRDSoEqr7d5Q7O_WqrHC6lRUVTMslUVDsWszlJsdXSIhAKUiz6VIn753nHPHOeoiFQUijUKeQogZRCBDGQsRAiYECISwTTFtOw3IKqGUf-pemay3k_RfmFrvqx_d-Zmpi-3KNPa1e6NWoOvRLbp5YW554W4JplTHrpeaojDlqbscx3FIUsA-kVHkMyyEv5oC-LLVpgGLOWHszL1mKlVqGFS1melcDVQhdH7ec772LuN-Mje3sLR43Rt0fvecN_32pl8PH_Hky7PJ28-Z_rZy0jnrow24W29syicyK5o7cG9vCzXR-uSBHm-Ns5JOcUnx_YYzMqVmhBNy6DmHnvfdc55f6pzO_9_JHxY7fwE1&sessionid=99961cd0-1b77-40aa-8cdd-bd1dc3495144
Navigated to https://identity.azurestaticapps.net/.auth/login/done
Navigated to https://orange-desert-095eaeb1e.azurestaticapps.net/.auth/complete
Navigated to https://orange-desert-095eaeb1e.azurestaticapps.net/?
```

It appears the app is consistently trying to open "/?" which puts it into an infinite loop. Anything obvious I have done wrong in the `routes.json`?

**Comment by mkarmark** [comment] 2020-11-23 21:10
Hi @akzaidi, I plugged that exact routes and platform error overrides config into my repo and I did not experience an infinite redirect loop as you mentioned, nor does the scenario sound problematic in anyway (it really should work). I also checked out https://orange-desert-095eaeb1e.azurestaticapps.net and didn't experience the infinite loop there either. Has the config changed since experiencing the loop? Is there a specific browser you are experiencing this issue with? I tried Chrome, Edge, and Firefox but don't have access to Safari, so I wonder if there is a discrepancy between how browsers interact with cookies.

**Comment by akzaidi** [comment] 2020-11-24 18:24
Thanks @mkarmark for the reply and for checking! Our users are using edge and chrome, so I don't think it's a browser specific issue.

It does seem hard to re-produce the error in general, but has been occurring for multiple users. It does seem to resolve if they use a brand new browser, so perhaps it is due to a mismatch from previously cached AAD authentication?

I did change the routes.json twice before landing on what I shared in the opening post. First I did not have the `platformformErrorOverrides`:

```json
{
  "routes": [
    {
      "route": "/login",
      "serve": "/.auth/login/aad"
    },
    {
      "route": "/login/github",
      "serve": "/.auth/login/github"
    },
    {
      "route": "/.auth/login/twitter",
      "statusCode": "401"
    },
    {
      "route": "/.auth/login/facebook",
      "statusCode": "401"
    },
    {
      "route": "/.auth/login/google",
      "statusCode": "401"
    },
    {
      "route": "/*",
      "serve": "/index.html",
      "allowedRoles": ["reader", "contributor", "authenticated"]
    }
  ]
}
```

which I added but initially had the status code to "301" instead of 302:

```json
{
  "routes": [
    {
      "route": "/login",
      "serve": "/.auth/login/aad"
    },
    {
      "route": "/login/github",
      "serve": "/.auth/login/github"
    },
    {
      "route": "/.auth/login/twitter",
      "statusCode": "401"
    },
    {
      "route": "/.auth/login/facebook",
      "statusCode": "401"
    },
    {
      "route": "/.auth/login/google",
      "statusCode": "401"
    },
    {
      "route": "/*",
      "serve": "/index.html",
      "allowedRoles": ["reader", "contributor", "authenticated"]
    }
  ],
    "platformErrorOverrides": [
        {
            "errorType": "Unauthenticated",
            "statusCode": "301",
            "serve": "/login"
        }
    ]
}
```

Would either of the previous configs explain why some users have cached login authentication that now lead to issues?

**Comment by jon-a-nygaard** [comment] 2021-09-16 13:53
@akzaidi Did you manage to find out what caused your login-loop and solve the issue? 🙂 

In case anyone comes across this issue for inspiration, the `platformErrorOverrides` seems to be deprecated and should be replaced with `responseOverrides`. See [Response Overrides](https://docs.microsoft.com/en-gb/azure/static-web-apps/configuration#response-overrides) for more information and example usage.

**Comment by akzaidi** [comment] 2021-09-16 16:59
Hi @jon-a-nygaard ! We haven't had the issue reoccur in a long while, so I'd like to say it's resolved, although I cannot remember the fix :-/ 

This is our current routes.json:

```json
{
  "routes": [
    {
      "route": "/login",
      "serve": "/.auth/login/aad"
    },
    {
      "route": "/login/github",
      "serve": "/.auth/login/github"
    },
    {
      "route": "/.auth/login/twitter",
      "statusCode": "401"
    },
    {
      "route": "/.auth/login/facebook",
      "statusCode": "401"
    },
    {
      "route": "/.auth/login/google",
      "statusCode": "401"
    },
    {
      "route": "/*",
      "allowedRoles": ["reader", "contributor", "authenticated"]
    }
  ],
    "platformErrorOverrides": [
        {
            "errorType": "Unauthenticated",
            "statusCode": 302,
            "serve": "/login"
        }
    ]
}
```

which has been working well. I'll update the `platformErrorOverrides` to `responseOverrides` now. Thanks!

**Comment by anthonychu** [comment] 2021-09-18 00:34
Note that `responseOverrides` is used in staticwebapp.config.json, which is the replacement for the deprecated routes.json file.

**Comment by simonaco** [comment] 2021-12-21 09:51
closing the issue as resolved, @jon-a-nygaard please reopen if you can still reproduce it. thank you!

**Closed by simonaco** 2021-12-21 09:51 UTC
Labels: AuthN/Z
