### ISSUE TITLE
Static Web App ------ Deployment Failure Reason: Failed to deploy the Azure Functions.

### ISSUE THREAD

**Issue by adam-javelin** [Azure/static-web-apps#622] opened 2021-11-05 06:02 UTC
Static Web app was running fine. Did a code push and now the stack is down and I cannot figure out why. I tried re-running the build but it always fails the same. 

build below

---End of Oryx build logs---
Function Runtime Information. OS: Linux, Functions Runtime: v3, Node version: 12.X
Finished building function app with Oryx
Zipping Api Artifacts
Done Zipping Api Artifacts
Zipping App Artifacts
Done Zipping App Artifacts
Uploading build artifacts.
Finished Upload. Polling on deployment.
Status: InProgress. Time: 0.3657797(s)
Status: InProgress. Time: 15.5921772(s)
Status: InProgress. Time: 31.5297017(s)
Status: Failed. Time: 46.7196347(s)
**Deployment Failed :(
Deployment Failure Reason: Failed to deploy the Azure Functions.**

![image](https://user-images.githubusercontent.com/79462674/140465547-21686448-ccd2-435a-bc0f-28d2ca08e684.png)

**Comment by adam-javelin** [comment] 2021-11-05 15:46
[logs_356.zip](https://github.com/Azure/static-web-apps/files/7487254/logs_356.zip)
Here are my logs. 

This has been working for several months. Then out of nowhere lastnight it just wouldn't build anymore.

**Comment by joslinmicrosoft** [comment] 2021-11-05 16:21
Hi @adam-javelin, sorry for the inconvenience! If you retry the deployment now do you still see errors? It seems like last night we had some issues deploying to Azure Functions, but they seem to have been resolved.

**Comment by adam-javelin** [comment] 2021-11-05 16:29
Thanks @joslinmicrosoft I did try a pull request to test a branch. I will update when I can get dev to build successfully. ATM dev is somehow working even the Azure Portal says its not. I'm hesitant to re-build right now because we have some users testing right now. I will build it again later today and post back. Thanks for your prompt reply.

**Comment by joslinmicrosoft** [comment] 2021-11-05 16:46
Good to hear the PR works! When you say that Portal says it's not working, do you mean within the Environments section it says "Failed" under the status? Just to clarify there, that status is about the latest deployment attempt, not the status of the live app. Failed builds/deployments do not update the app, so your currently live app should reflect the changes from your last _successful_ deployment.

**Comment by adam-javelin** [comment] 2021-11-05 17:17
Ok its all good now just built to main and 👍 .

**Comment by ckriutz** [comment] 2021-11-19 15:33
I don't know if it's possible to re-open this, or look at it, but I'm experiencing the same error. Almost exactly.
The deployment worked before I added the function, but not after. No real reason or explanation, just fails.

**Comment by sig9** [comment] 2021-11-19 15:46
we are having the same issue starting yesterday

**Comment by adam-javelin** [comment] 2021-11-19 15:56
Yeah it would be nice to understand what is causing this.

**Comment by miwebst** [comment] 2021-11-19 17:02
We are investigating, does look like an issue with Azure Function deployment.

**Comment by miwebst** [comment] 2021-11-19 21:28
As an update we've found a potential root cause for the issues we are seeing and working to address it. Will continue to update here as we know more.

One thing to note is this only affects new SWA deployments with Functions, all existing SWA's with Azure Functions should be unaffected.

**Comment by miwebst** [comment] 2021-11-19 23:37
A fix has been found and applied, all new Function deployments should begin to work again. Sorry for the inconvenience!

**Closed** 2021-11-19 23:41 UTC
