### ISSUE TITLE
Api's proxy needs to pass thru 302

### ISSUE THREAD

**Issue by keesschollaart81** [Azure/static-web-apps#39] opened 2020-05-31 07:24 UTC
Working on this example:
https://github.com/keesschollaart81/Contact-Form-With-Azure-Static-Web-Apps/blob/master/api/ContactForm/index.js#L25-L30

I discovered two things when working with a 302 response header.
1) It does not pass thru the header, instead (the reverse proxy?) returns the response of the redirected location
2) When you provide a wrong location, for example a relative url, it gives a 404.

The linked demo does work locally but breaks in the cloud.

My initial problem was the 404 of 2. It took me quite some time to figure out what was going on as there is no (cloud) logging. There's also little to no documentation on this proxy / architecture / behaviour of the Static Web App Api.

Link to thread on Twitter: https://twitter.com/nthonyChu/status/1266855455642378240

**Comment by miwebst** [comment] 2020-06-01 16:10
We will take a look at this, do you have a sample app that is currently exhibiting this behavior?

**Comment by keesschollaart81** [comment] 2020-06-01 17:30
The first link points to a simple contact form example. The code you'll find there does work locally but breaks in Azure. Specifically the linked lines (25-30). I have  fixed version working, the fix is not to redirect to a local URL (`/thanks`) but to a full url (`https://example.com/thanks.html`)

**Comment by anthonychu** [comment] 2020-06-01 21:20
I have an example here as well: https://github.com/anthonychu/test-aswa-api-redirect

This currently returns a 404 because the proxy is following the redirect and can't find `/thankyou.html`.

```
curl -v https://delightful-island-0d63ac010.azurestaticapps.net/api/redirect
```

And this currently returns 200 because the proxy is following the redirect and returning the contents from `https://delightful-island-0d63ac010.azurestaticapps.net/thankyou.html`.

```
curl -v https://delightful-island-0d63ac010.azurestaticapps.net/api/redirectabsolute
```

The expected behavior for both is to return a 302 with the location header returned from the function.

**Comment by miwebst** [comment] 2020-06-03 01:30
This should be fixed globally now. Sorry for the inconvenience!

**Closed** 2020-06-06 00:24 UTC
